//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem.Sync.Connector.Xing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sem.Sync.Connector.Xing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... adding {0} contacts to list of currently {1} contacts..
        /// </summary>
        internal static string uiAddingContacts {
            get {
                return ResourceManager.GetString("uiAddingContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloaded: .
        /// </summary>
        internal static string uiDownloaded {
            get {
                return ResourceManager.GetString("uiDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} elements found - downloading vCards ....
        /// </summary>
        internal static string uiDownloadingVCards {
            get {
                return ResourceManager.GetString("uiDownloadingVCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log on FAILED in for user {0}..
        /// </summary>
        internal static string uiLogInFailed {
            get {
                return ResourceManager.GetString("uiLogInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log on for user {0}....
        /// </summary>
        internal static string uiLogInForUser {
            get {
                return ResourceManager.GetString("uiLogInForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log on succeeded in for user {0}..
        /// </summary>
        internal static string uiLogInSucceeded {
            get {
                return ResourceManager.GetString("uiLogInSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This implementation does not support altering contacts - you can only query contacts..
        /// </summary>
        internal static string uiNoAlteringImplemented {
            get {
                return ResourceManager.GetString("uiNoAlteringImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading contacts list....
        /// </summary>
        internal static string uiReadingContactList {
            get {
                return ResourceManager.GetString("uiReadingContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xing needs your credentials to cooperate..
        /// </summary>
        internal static string uiXingNeedsCredentials {
            get {
                return ResourceManager.GetString("uiXingNeedsCredentials", resourceCulture);
            }
        }
    }
}
