//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/", ConfigurationName="FieldManagementSR.FieldManagementService")]
    public interface FieldManagementService {
        
        // CODEGEN: Generating message contract since the operation FieldManagementReadAll is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/urn:crmondemand/ws/odesabs/FieldManagement/:FieldManagementReadAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAllResponse FieldManagementReadAll(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAllRequest request);
        
        // CODEGEN: Generating message contract since the operation FieldManagementRead is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/urn:crmondemand/ws/odesabs/FieldManagement/:FieldManagementRead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadResponse FieldManagementRead(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadRequest request);
        
        // CODEGEN: Generating message contract since the operation FieldManagementUpsert is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/urn:crmondemand/ws/odesabs/FieldManagement/:FieldManagementUpsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsertResponse FieldManagementUpsert(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsertRequest request);
        
        // CODEGEN: Generating message contract since the operation FieldManagementCreate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/urn:crmondemand/ws/odesabs/FieldManagement/:FieldManagementCreate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreateResponse FieldManagementCreate(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementReadAll_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
    public partial class CustomFieldTranslationData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string languageCodeField;
        
        private string displayNameField;
        
        private string validationErrorMsgField;
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
                this.RaisePropertyChanged("LanguageCode");
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        /// <remarks/>
        public string ValidationErrorMsg {
            get {
                return this.validationErrorMsgField;
            }
            set {
                this.validationErrorMsgField = value;
                this.RaisePropertyChanged("ValidationErrorMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
    public partial class CustomFieldData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string objectNameField;
        
        private string displayNameField;
        
        private string customFieldTypeField;
        
        private string integrationTagField;
        
        private bool requiredField;
        
        private bool requiredFieldSpecified;
        
        private bool readOnlyField;
        
        private bool readOnlyFieldSpecified;
        
        private string defaultValueField;
        
        private string customFieldValidationField;
        
        private bool postDefaultField;
        
        private bool postDefaultFieldSpecified;
        
        private string validationErrorMsgField;
        
        private CustomFieldTranslationData[] listOfCustomFieldTranslationsField;
        
        /// <remarks/>
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        /// <remarks/>
        public string CustomFieldType {
            get {
                return this.customFieldTypeField;
            }
            set {
                this.customFieldTypeField = value;
                this.RaisePropertyChanged("CustomFieldType");
            }
        }
        
        /// <remarks/>
        public string IntegrationTag {
            get {
                return this.integrationTagField;
            }
            set {
                this.integrationTagField = value;
                this.RaisePropertyChanged("IntegrationTag");
            }
        }
        
        /// <remarks/>
        public bool Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
                this.RaisePropertyChanged("Required");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequiredSpecified {
            get {
                return this.requiredFieldSpecified;
            }
            set {
                this.requiredFieldSpecified = value;
                this.RaisePropertyChanged("RequiredSpecified");
            }
        }
        
        /// <remarks/>
        public bool ReadOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
                this.RaisePropertyChanged("ReadOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadOnlySpecified {
            get {
                return this.readOnlyFieldSpecified;
            }
            set {
                this.readOnlyFieldSpecified = value;
                this.RaisePropertyChanged("ReadOnlySpecified");
            }
        }
        
        /// <remarks/>
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
                this.RaisePropertyChanged("DefaultValue");
            }
        }
        
        /// <remarks/>
        public string CustomFieldValidation {
            get {
                return this.customFieldValidationField;
            }
            set {
                this.customFieldValidationField = value;
                this.RaisePropertyChanged("CustomFieldValidation");
            }
        }
        
        /// <remarks/>
        public bool PostDefault {
            get {
                return this.postDefaultField;
            }
            set {
                this.postDefaultField = value;
                this.RaisePropertyChanged("PostDefault");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostDefaultSpecified {
            get {
                return this.postDefaultFieldSpecified;
            }
            set {
                this.postDefaultFieldSpecified = value;
                this.RaisePropertyChanged("PostDefaultSpecified");
            }
        }
        
        /// <remarks/>
        public string ValidationErrorMsg {
            get {
                return this.validationErrorMsgField;
            }
            set {
                this.validationErrorMsgField = value;
                this.RaisePropertyChanged("ValidationErrorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomFieldTranslation", IsNullable=false)]
        public CustomFieldTranslationData[] ListOfCustomFieldTranslations {
            get {
                return this.listOfCustomFieldTranslationsField;
            }
            set {
                this.listOfCustomFieldTranslationsField = value;
                this.RaisePropertyChanged("ListOfCustomFieldTranslations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/query")]
    public partial class FieldTranslationQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Empty languageCodeField;
        
        private Empty displayNameField;
        
        private Empty validationErrorMsgField;
        
        /// <remarks/>
        public Empty LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
                this.RaisePropertyChanged("LanguageCode");
            }
        }
        
        /// <remarks/>
        public Empty DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        /// <remarks/>
        public Empty ValidationErrorMsg {
            get {
                return this.validationErrorMsgField;
            }
            set {
                this.validationErrorMsgField = value;
                this.RaisePropertyChanged("ValidationErrorMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/query")]
    public partial class Empty : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/query")]
    public partial class FieldQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private Empty displayNameField;
        
        private Empty fieldTypeField;
        
        private Empty integrationTagField;
        
        private Empty requiredField;
        
        private Empty readOnlyField;
        
        private Empty defaultValueField;
        
        private Empty fieldValidationField;
        
        private Empty postDefaultField;
        
        private Empty validationErrorMsgField;
        
        private FieldTranslationQuery[] listOfFieldTranslationsField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public Empty DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        /// <remarks/>
        public Empty FieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
                this.RaisePropertyChanged("FieldType");
            }
        }
        
        /// <remarks/>
        public Empty IntegrationTag {
            get {
                return this.integrationTagField;
            }
            set {
                this.integrationTagField = value;
                this.RaisePropertyChanged("IntegrationTag");
            }
        }
        
        /// <remarks/>
        public Empty Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
                this.RaisePropertyChanged("Required");
            }
        }
        
        /// <remarks/>
        public Empty ReadOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
                this.RaisePropertyChanged("ReadOnly");
            }
        }
        
        /// <remarks/>
        public Empty DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
                this.RaisePropertyChanged("DefaultValue");
            }
        }
        
        /// <remarks/>
        public Empty FieldValidation {
            get {
                return this.fieldValidationField;
            }
            set {
                this.fieldValidationField = value;
                this.RaisePropertyChanged("FieldValidation");
            }
        }
        
        /// <remarks/>
        public Empty PostDefault {
            get {
                return this.postDefaultField;
            }
            set {
                this.postDefaultField = value;
                this.RaisePropertyChanged("PostDefault");
            }
        }
        
        /// <remarks/>
        public Empty ValidationErrorMsg {
            get {
                return this.validationErrorMsgField;
            }
            set {
                this.validationErrorMsgField = value;
                this.RaisePropertyChanged("ValidationErrorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FieldTranslation", IsNullable=false)]
        public FieldTranslationQuery[] ListOfFieldTranslations {
            get {
                return this.listOfFieldTranslationsField;
            }
            set {
                this.listOfFieldTranslationsField = value;
                this.RaisePropertyChanged("ListOfFieldTranslations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/query")]
    public partial class FieldSetQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string objectNameField;
        
        private FieldQuery[] listOfFieldsField;
        
        /// <remarks/>
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
        public FieldQuery[] ListOfFields {
            get {
                return this.listOfFieldsField;
            }
            set {
                this.listOfFieldsField = value;
                this.RaisePropertyChanged("ListOfFields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
    public partial class FieldTranslationData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string languageCodeField;
        
        private string displayNameField;
        
        private string validationErrorMsgField;
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
                this.RaisePropertyChanged("LanguageCode");
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        /// <remarks/>
        public string ValidationErrorMsg {
            get {
                return this.validationErrorMsgField;
            }
            set {
                this.validationErrorMsgField = value;
                this.RaisePropertyChanged("ValidationErrorMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
    public partial class FieldData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string displayNameField;
        
        private string fieldTypeField;
        
        private string integrationTagField;
        
        private bool requiredField;
        
        private bool requiredFieldSpecified;
        
        private bool readOnlyField;
        
        private bool readOnlyFieldSpecified;
        
        private string defaultValueField;
        
        private string fieldValidationField;
        
        private bool postDefaultField;
        
        private bool postDefaultFieldSpecified;
        
        private string validationErrorMsgField;
        
        private FieldTranslationData[] listOfFieldTranslationsField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        /// <remarks/>
        public string FieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
                this.RaisePropertyChanged("FieldType");
            }
        }
        
        /// <remarks/>
        public string IntegrationTag {
            get {
                return this.integrationTagField;
            }
            set {
                this.integrationTagField = value;
                this.RaisePropertyChanged("IntegrationTag");
            }
        }
        
        /// <remarks/>
        public bool Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
                this.RaisePropertyChanged("Required");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequiredSpecified {
            get {
                return this.requiredFieldSpecified;
            }
            set {
                this.requiredFieldSpecified = value;
                this.RaisePropertyChanged("RequiredSpecified");
            }
        }
        
        /// <remarks/>
        public bool ReadOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
                this.RaisePropertyChanged("ReadOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadOnlySpecified {
            get {
                return this.readOnlyFieldSpecified;
            }
            set {
                this.readOnlyFieldSpecified = value;
                this.RaisePropertyChanged("ReadOnlySpecified");
            }
        }
        
        /// <remarks/>
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
                this.RaisePropertyChanged("DefaultValue");
            }
        }
        
        /// <remarks/>
        public string FieldValidation {
            get {
                return this.fieldValidationField;
            }
            set {
                this.fieldValidationField = value;
                this.RaisePropertyChanged("FieldValidation");
            }
        }
        
        /// <remarks/>
        public bool PostDefault {
            get {
                return this.postDefaultField;
            }
            set {
                this.postDefaultField = value;
                this.RaisePropertyChanged("PostDefault");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostDefaultSpecified {
            get {
                return this.postDefaultFieldSpecified;
            }
            set {
                this.postDefaultFieldSpecified = value;
                this.RaisePropertyChanged("PostDefaultSpecified");
            }
        }
        
        /// <remarks/>
        public string ValidationErrorMsg {
            get {
                return this.validationErrorMsgField;
            }
            set {
                this.validationErrorMsgField = value;
                this.RaisePropertyChanged("ValidationErrorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FieldTranslation", IsNullable=false)]
        public FieldTranslationData[] ListOfFieldTranslations {
            get {
                return this.listOfFieldTranslationsField;
            }
            set {
                this.listOfFieldTranslationsField = value;
                this.RaisePropertyChanged("ListOfFieldTranslations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
    public partial class FieldSetData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string objectNameField;
        
        private FieldData[] listOfFieldsField;
        
        /// <remarks/>
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
        public FieldData[] ListOfFields {
            get {
                return this.listOfFieldsField;
            }
            set {
                this.listOfFieldsField = value;
                this.RaisePropertyChanged("ListOfFields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementReadAll_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FieldSetData[] listOfFieldSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FieldSet", IsNullable=false)]
        public FieldSetData[] ListOfFieldSet {
            get {
                return this.listOfFieldSetField;
            }
            set {
                this.listOfFieldSetField = value;
                this.RaisePropertyChanged("ListOfFieldSet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FieldManagementReadAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/", Order=0)]
        public Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAll_Input FieldManagementReadAll_Input;
        
        public FieldManagementReadAllRequest() {
        }
        
        public FieldManagementReadAllRequest(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAll_Input FieldManagementReadAll_Input) {
            this.FieldManagementReadAll_Input = FieldManagementReadAll_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FieldManagementReadAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/", Order=0)]
        public Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAll_Output FieldManagementReadAll_Output;
        
        public FieldManagementReadAllResponse() {
        }
        
        public FieldManagementReadAllResponse(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAll_Output FieldManagementReadAll_Output) {
            this.FieldManagementReadAll_Output = FieldManagementReadAll_Output;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementRead_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FieldSetQuery fieldSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/query", Order=0)]
        public FieldSetQuery FieldSet {
            get {
                return this.fieldSetField;
            }
            set {
                this.fieldSetField = value;
                this.RaisePropertyChanged("FieldSet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementRead_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FieldSetData[] listOfFieldSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FieldSet", IsNullable=false)]
        public FieldSetData[] ListOfFieldSet {
            get {
                return this.listOfFieldSetField;
            }
            set {
                this.listOfFieldSetField = value;
                this.RaisePropertyChanged("ListOfFieldSet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FieldManagementReadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/", Order=0)]
        public Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementRead_Input FieldManagementRead_Input;
        
        public FieldManagementReadRequest() {
        }
        
        public FieldManagementReadRequest(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementRead_Input FieldManagementRead_Input) {
            this.FieldManagementRead_Input = FieldManagementRead_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FieldManagementReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/", Order=0)]
        public Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementRead_Output FieldManagementRead_Output;
        
        public FieldManagementReadResponse() {
        }
        
        public FieldManagementReadResponse(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementRead_Output FieldManagementRead_Output) {
            this.FieldManagementRead_Output = FieldManagementRead_Output;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementUpsert_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FieldSetData fieldSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data", Order=0)]
        public FieldSetData FieldSet {
            get {
                return this.fieldSetField;
            }
            set {
                this.fieldSetField = value;
                this.RaisePropertyChanged("FieldSet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementUpsert_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FieldManagementUpsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/", Order=0)]
        public Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsert_Input FieldManagementUpsert_Input;
        
        public FieldManagementUpsertRequest() {
        }
        
        public FieldManagementUpsertRequest(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsert_Input FieldManagementUpsert_Input) {
            this.FieldManagementUpsert_Input = FieldManagementUpsert_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FieldManagementUpsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/", Order=0)]
        public Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsert_Output FieldManagementUpsert_Output;
        
        public FieldManagementUpsertResponse() {
        }
        
        public FieldManagementUpsertResponse(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsert_Output FieldManagementUpsert_Output) {
            this.FieldManagementUpsert_Output = FieldManagementUpsert_Output;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementCreate_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CustomFieldData customFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data", Order=0)]
        public CustomFieldData CustomField {
            get {
                return this.customFieldField;
            }
            set {
                this.customFieldField = value;
                this.RaisePropertyChanged("CustomField");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementCreate_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FieldManagementCreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/", Order=0)]
        public Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreate_Input FieldManagementCreate_Input;
        
        public FieldManagementCreateRequest() {
        }
        
        public FieldManagementCreateRequest(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreate_Input FieldManagementCreate_Input) {
            this.FieldManagementCreate_Input = FieldManagementCreate_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FieldManagementCreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/", Order=0)]
        public Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreate_Output FieldManagementCreate_Output;
        
        public FieldManagementCreateResponse() {
        }
        
        public FieldManagementCreateResponse(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreate_Output FieldManagementCreate_Output) {
            this.FieldManagementCreate_Output = FieldManagementCreate_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FieldManagementServiceChannel : Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FieldManagementServiceClient : System.ServiceModel.ClientBase<Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementService>, Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementService {
        
        public FieldManagementServiceClient() {
        }
        
        public FieldManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FieldManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FieldManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FieldManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAllResponse Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementService.FieldManagementReadAll(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAllRequest request) {
            return base.Channel.FieldManagementReadAll(request);
        }
        
        public Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAll_Output FieldManagementReadAll(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAll_Input FieldManagementReadAll_Input) {
            Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAllRequest inValue = new Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAllRequest();
            inValue.FieldManagementReadAll_Input = FieldManagementReadAll_Input;
            Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadAllResponse retVal = ((Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementService)(this)).FieldManagementReadAll(inValue);
            return retVal.FieldManagementReadAll_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadResponse Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementService.FieldManagementRead(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadRequest request) {
            return base.Channel.FieldManagementRead(request);
        }
        
        public Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementRead_Output FieldManagementRead(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementRead_Input FieldManagementRead_Input) {
            Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadRequest inValue = new Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadRequest();
            inValue.FieldManagementRead_Input = FieldManagementRead_Input;
            Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementReadResponse retVal = ((Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementService)(this)).FieldManagementRead(inValue);
            return retVal.FieldManagementRead_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsertResponse Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementService.FieldManagementUpsert(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsertRequest request) {
            return base.Channel.FieldManagementUpsert(request);
        }
        
        public Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsert_Output FieldManagementUpsert(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsert_Input FieldManagementUpsert_Input) {
            Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsertRequest inValue = new Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsertRequest();
            inValue.FieldManagementUpsert_Input = FieldManagementUpsert_Input;
            Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementUpsertResponse retVal = ((Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementService)(this)).FieldManagementUpsert(inValue);
            return retVal.FieldManagementUpsert_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreateResponse Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementService.FieldManagementCreate(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreateRequest request) {
            return base.Channel.FieldManagementCreate(request);
        }
        
        public Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreate_Output FieldManagementCreate(Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreate_Input FieldManagementCreate_Input) {
            Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreateRequest inValue = new Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreateRequest();
            inValue.FieldManagementCreate_Input = FieldManagementCreate_Input;
            Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementCreateResponse retVal = ((Sdx.Sync.Connector.OracleCrmOnDemand.FieldManagementSR.FieldManagementService)(this)).FieldManagementCreate(inValue);
            return retVal.FieldManagementCreate_Output;
        }
    }
}
