//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem.Sync.SyncBase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sem.Sync.SyncBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem finding the Primary Interop Assemblies for Office. Do you want to open the download page for this missing dependency?.
        /// </summary>
        public static string MissingInteropQuestion {
            get {
                return ResourceManager.GetString("MissingInteropQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string MissingInteropQuestionTitle {
            get {
                return ResourceManager.GetString("MissingInteropQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding element ....
        /// </summary>
        public static string uiAddingElement {
            get {
                return ResourceManager.GetString("uiAddingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding missing element ....
        /// </summary>
        public static string uiAddingMissingElement {
            get {
                return ResourceManager.GetString("uiAddingMissingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding missing elements ....
        /// </summary>
        public static string uiAddingMissingElements {
            get {
                return ResourceManager.GetString("uiAddingMissingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding {0} elements ....
        /// </summary>
        public static string uiAddingXElements {
            get {
                return ResourceManager.GetString("uiAddingXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding {0} elements ....
        /// </summary>
        public static string uiAddingXMissingElements {
            get {
                return ResourceManager.GetString("uiAddingXMissingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element added.
        /// </summary>
        public static string uiElementAdded {
            get {
                return ResourceManager.GetString("uiElementAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element skipped.
        /// </summary>
        public static string uiElementSkipped {
            get {
                return ResourceManager.GetString("uiElementSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files deleted.
        /// </summary>
        public static string uiFilesDeleted {
            get {
                return ResourceManager.GetString("uiFilesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging on ....
        /// </summary>
        public static string uiLogOn {
            get {
                return ResourceManager.GetString("uiLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normalizing ....
        /// </summary>
        public static string uiNormalizing {
            get {
                return ResourceManager.GetString("uiNormalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of sync engine is outdated - please update!.
        /// </summary>
        public static string uiOutOfDateVersion {
            get {
                return ResourceManager.GetString("uiOutOfDateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processing canceled..
        /// </summary>
        public static string uiProcessingCanceled {
            get {
                return ResourceManager.GetString("uiProcessingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading elements ....
        /// </summary>
        public static string uiReadingElements {
            get {
                return ResourceManager.GetString("uiReadingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorted.
        /// </summary>
        public static string uiSorted {
            get {
                return ResourceManager.GetString("uiSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorting ....
        /// </summary>
        public static string uiSorting {
            get {
                return ResourceManager.GetString("uiSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start processing {0} sync commands....
        /// </summary>
        public static string uiStartingProcessing {
            get {
                return ResourceManager.GetString("uiStartingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writing Elements.
        /// </summary>
        public static string uiWritingElements {
            get {
                return ResourceManager.GetString("uiWritingElements", resourceCulture);
            }
        }
    }
}
