//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem.Sync.Connector.Outlook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sem.Sync.Connector.Outlook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem finding the Primary Interop Assemblies for Office 2003. Do you want to open the download page for this missing dependency?.
        /// </summary>
        internal static string MissingInteropQuestion {
            get {
                return ResourceManager.GetString("MissingInteropQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string MissingInteropQuestionTitle {
            get {
                return ResourceManager.GetString("MissingInteropQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding {0} elements ....
        /// </summary>
        internal static string uiAddingXElements {
            get {
                return ResourceManager.GetString("uiAddingXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comparing ....
        /// </summary>
        internal static string uiComparing {
            get {
                return ResourceManager.GetString("uiComparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact updated..
        /// </summary>
        internal static string uiContactUpdated {
            get {
                return ResourceManager.GetString("uiContactUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at name {0}: {1}.
        /// </summary>
        internal static string uiErrorAtName {
            get {
                return ResourceManager.GetString("uiErrorAtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging on ....
        /// </summary>
        internal static string uiLogginIn {
            get {
                return ResourceManager.GetString("uiLogginIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no outlook folder selected.
        /// </summary>
        internal static string uiNoFolderSelected {
            get {
                return ResourceManager.GetString("uiNoFolderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preparing list ....
        /// </summary>
        internal static string uiPreparingList {
            get {
                return ResourceManager.GetString("uiPreparingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problem accessing outlook store at name {0}: {1}.
        /// </summary>
        internal static string uiProblemAccessingOutlookStore {
            get {
                return ResourceManager.GetString("uiProblemAccessingOutlookStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading ....
        /// </summary>
        internal static string uiReadingContact {
            get {
                return ResourceManager.GetString("uiReadingContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove duplicates finished.
        /// </summary>
        internal static string uiRemoveDuplicates {
            get {
                return ResourceManager.GetString("uiRemoveDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removing ....
        /// </summary>
        internal static string uiRemoving {
            get {
                return ResourceManager.GetString("uiRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching ....
        /// </summary>
        internal static string uiSearching {
            get {
                return ResourceManager.GetString("uiSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} elements added.
        /// </summary>
        internal static string uiXElementsAdded {
            get {
                return ResourceManager.GetString("uiXElementsAdded", resourceCulture);
            }
        }
    }
}
