//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem.Sync.Connector.OnlineStorage.ContactService2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://svenerikmatzen.com/Sem/Sync/OnlineStorage", ConfigurationName="ContactService2.IContactService")]
    public interface IContactService {
        
        // CODEGEN: Parameter 'GetAllResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://svenerikmatzen.com/Sem/Sync/OnlineStorage/IContactService/GetAll", ReplyAction="http://svenerikmatzen.com/Sem/Sync/OnlineStorage/IContactService/GetAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StdElement))]
        Sem.Sync.Connector.OnlineStorage.ContactService2.GetAllResponse GetAll(Sem.Sync.Connector.OnlineStorage.ContactService2.GetAllRequest request);
        
        // CODEGEN: Parameter 'elements' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://svenerikmatzen.com/Sem/Sync/OnlineStorage/IContactService/WriteFullList", ReplyAction="http://svenerikmatzen.com/Sem/Sync/OnlineStorage/IContactService/WriteFullListRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StdElement))]
        Sem.Sync.Connector.OnlineStorage.ContactService2.WriteFullListResponse WriteFullList(Sem.Sync.Connector.OnlineStorage.ContactService2.WriteFullListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.OnlineStorage2")]
    public partial class ContactListContainer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StdContact[] contactListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase")]
        public StdContact[] ContactList {
            get {
                return this.contactListField;
            }
            set {
                this.contactListField = value;
                this.RaisePropertyChanged("ContactList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase")]
    public partial class StdContact : StdElement {
        
        private string additionalTextDatak__BackingFieldField;
        
        private AddressDetail businessAddressPrimaryk__BackingFieldField;
        
        private AddressDetail businessAddressSecondaryk__BackingFieldField;
        
        private BusinessCertificate[] businessCertificatesk__BackingFieldField;
        
        private string businessCompanyNamek__BackingFieldField;
        
        private string businessDepartmentk__BackingFieldField;
        
        private string businessEmailPrimaryk__BackingFieldField;
        
        private string businessEmailSecondaryk__BackingFieldField;
        
        private BusinessHistoryEntry[] businessHistoryEntriesk__BackingFieldField;
        
        private string businessHomepagek__BackingFieldField;
        
        private InstantMessengerAddresses businessInstantMessengerAddressesk__BackingFieldField;
        
        private PhoneNumber businessPhoneMobilek__BackingFieldField;
        
        private string businessPositionk__BackingFieldField;
        
        private string[] categoriesk__BackingFieldField;
        
        private ContactReference[] contactsk__BackingFieldField;
        
        private System.DateTime dateOfBirthk__BackingFieldField;
        
        private ImageEntry[] imageEntriesk__BackingFieldField;
        
        private LanguageKnowledge[] languageKnowledgesk__BackingFieldField;
        
        private PersonName namek__BackingFieldField;
        
        private Gender personGenderk__BackingFieldField;
        
        private AddressDetail personalAddressPrimaryk__BackingFieldField;
        
        private AddressDetail personalAddressSecondaryk__BackingFieldField;
        
        private string personalEmailPrimaryk__BackingFieldField;
        
        private string personalEmailSecondaryk__BackingFieldField;
        
        private string personalHomepagek__BackingFieldField;
        
        private InstantMessengerAddresses personalInstantMessengerAddressesk__BackingFieldField;
        
        private PhoneNumber personalPhoneMobilek__BackingFieldField;
        
        private byte[] pictureDatak__BackingFieldField;
        
        private string pictureNamek__BackingFieldField;
        
        private RelationshipStatus relationshipStatusk__BackingFieldField;
        
        private System.Data.DataSet sourceSpecificAttributesk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<AdditionalTextData>k__BackingField", IsNullable=true, Order=0)]
        public string AdditionalTextDatak__BackingField {
            get {
                return this.additionalTextDatak__BackingFieldField;
            }
            set {
                this.additionalTextDatak__BackingFieldField = value;
                this.RaisePropertyChanged("AdditionalTextDatak__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<BusinessAddressPrimary>k__BackingField", IsNullable=true, Order=1)]
        public AddressDetail BusinessAddressPrimaryk__BackingField {
            get {
                return this.businessAddressPrimaryk__BackingFieldField;
            }
            set {
                this.businessAddressPrimaryk__BackingFieldField = value;
                this.RaisePropertyChanged("BusinessAddressPrimaryk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<BusinessAddressSecondary>k__BackingField", IsNullable=true, Order=2)]
        public AddressDetail BusinessAddressSecondaryk__BackingField {
            get {
                return this.businessAddressSecondaryk__BackingFieldField;
            }
            set {
                this.businessAddressSecondaryk__BackingFieldField = value;
                this.RaisePropertyChanged("BusinessAddressSecondaryk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<BusinessCertificates>k__BackingField", IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
        public BusinessCertificate[] BusinessCertificatesk__BackingField {
            get {
                return this.businessCertificatesk__BackingFieldField;
            }
            set {
                this.businessCertificatesk__BackingFieldField = value;
                this.RaisePropertyChanged("BusinessCertificatesk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<BusinessCompanyName>k__BackingField", IsNullable=true, Order=4)]
        public string BusinessCompanyNamek__BackingField {
            get {
                return this.businessCompanyNamek__BackingFieldField;
            }
            set {
                this.businessCompanyNamek__BackingFieldField = value;
                this.RaisePropertyChanged("BusinessCompanyNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<BusinessDepartment>k__BackingField", IsNullable=true, Order=5)]
        public string BusinessDepartmentk__BackingField {
            get {
                return this.businessDepartmentk__BackingFieldField;
            }
            set {
                this.businessDepartmentk__BackingFieldField = value;
                this.RaisePropertyChanged("BusinessDepartmentk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<BusinessEmailPrimary>k__BackingField", IsNullable=true, Order=6)]
        public string BusinessEmailPrimaryk__BackingField {
            get {
                return this.businessEmailPrimaryk__BackingFieldField;
            }
            set {
                this.businessEmailPrimaryk__BackingFieldField = value;
                this.RaisePropertyChanged("BusinessEmailPrimaryk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<BusinessEmailSecondary>k__BackingField", IsNullable=true, Order=7)]
        public string BusinessEmailSecondaryk__BackingField {
            get {
                return this.businessEmailSecondaryk__BackingFieldField;
            }
            set {
                this.businessEmailSecondaryk__BackingFieldField = value;
                this.RaisePropertyChanged("BusinessEmailSecondaryk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<BusinessHistoryEntries>k__BackingField", IsNullable=true, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
        public BusinessHistoryEntry[] BusinessHistoryEntriesk__BackingField {
            get {
                return this.businessHistoryEntriesk__BackingFieldField;
            }
            set {
                this.businessHistoryEntriesk__BackingFieldField = value;
                this.RaisePropertyChanged("BusinessHistoryEntriesk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<BusinessHomepage>k__BackingField", IsNullable=true, Order=9)]
        public string BusinessHomepagek__BackingField {
            get {
                return this.businessHomepagek__BackingFieldField;
            }
            set {
                this.businessHomepagek__BackingFieldField = value;
                this.RaisePropertyChanged("BusinessHomepagek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<BusinessInstantMessengerAddresses>k__BackingField", IsNullable=true, Order=10)]
        public InstantMessengerAddresses BusinessInstantMessengerAddressesk__BackingField {
            get {
                return this.businessInstantMessengerAddressesk__BackingFieldField;
            }
            set {
                this.businessInstantMessengerAddressesk__BackingFieldField = value;
                this.RaisePropertyChanged("BusinessInstantMessengerAddressesk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<BusinessPhoneMobile>k__BackingField", IsNullable=true, Order=11)]
        public PhoneNumber BusinessPhoneMobilek__BackingField {
            get {
                return this.businessPhoneMobilek__BackingFieldField;
            }
            set {
                this.businessPhoneMobilek__BackingFieldField = value;
                this.RaisePropertyChanged("BusinessPhoneMobilek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<BusinessPosition>k__BackingField", IsNullable=true, Order=12)]
        public string BusinessPositionk__BackingField {
            get {
                return this.businessPositionk__BackingFieldField;
            }
            set {
                this.businessPositionk__BackingFieldField = value;
                this.RaisePropertyChanged("BusinessPositionk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<Categories>k__BackingField", IsNullable=true, Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] Categoriesk__BackingField {
            get {
                return this.categoriesk__BackingFieldField;
            }
            set {
                this.categoriesk__BackingFieldField = value;
                this.RaisePropertyChanged("Categoriesk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<Contacts>k__BackingField", IsNullable=true, Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
        public ContactReference[] Contactsk__BackingField {
            get {
                return this.contactsk__BackingFieldField;
            }
            set {
                this.contactsk__BackingFieldField = value;
                this.RaisePropertyChanged("Contactsk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DateOfBirth>k__BackingField", Order=15)]
        public System.DateTime DateOfBirthk__BackingField {
            get {
                return this.dateOfBirthk__BackingFieldField;
            }
            set {
                this.dateOfBirthk__BackingFieldField = value;
                this.RaisePropertyChanged("DateOfBirthk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<ImageEntries>k__BackingField", IsNullable=true, Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
        public ImageEntry[] ImageEntriesk__BackingField {
            get {
                return this.imageEntriesk__BackingFieldField;
            }
            set {
                this.imageEntriesk__BackingFieldField = value;
                this.RaisePropertyChanged("ImageEntriesk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<LanguageKnowledges>k__BackingField", IsNullable=true, Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
        public LanguageKnowledge[] LanguageKnowledgesk__BackingField {
            get {
                return this.languageKnowledgesk__BackingFieldField;
            }
            set {
                this.languageKnowledgesk__BackingFieldField = value;
                this.RaisePropertyChanged("LanguageKnowledgesk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Name>k__BackingField", IsNullable=true, Order=18)]
        public PersonName Namek__BackingField {
            get {
                return this.namek__BackingFieldField;
            }
            set {
                this.namek__BackingFieldField = value;
                this.RaisePropertyChanged("Namek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<PersonGender>k__BackingField", Order=19)]
        public Gender PersonGenderk__BackingField {
            get {
                return this.personGenderk__BackingFieldField;
            }
            set {
                this.personGenderk__BackingFieldField = value;
                this.RaisePropertyChanged("PersonGenderk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<PersonalAddressPrimary>k__BackingField", IsNullable=true, Order=20)]
        public AddressDetail PersonalAddressPrimaryk__BackingField {
            get {
                return this.personalAddressPrimaryk__BackingFieldField;
            }
            set {
                this.personalAddressPrimaryk__BackingFieldField = value;
                this.RaisePropertyChanged("PersonalAddressPrimaryk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<PersonalAddressSecondary>k__BackingField", IsNullable=true, Order=21)]
        public AddressDetail PersonalAddressSecondaryk__BackingField {
            get {
                return this.personalAddressSecondaryk__BackingFieldField;
            }
            set {
                this.personalAddressSecondaryk__BackingFieldField = value;
                this.RaisePropertyChanged("PersonalAddressSecondaryk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<PersonalEmailPrimary>k__BackingField", IsNullable=true, Order=22)]
        public string PersonalEmailPrimaryk__BackingField {
            get {
                return this.personalEmailPrimaryk__BackingFieldField;
            }
            set {
                this.personalEmailPrimaryk__BackingFieldField = value;
                this.RaisePropertyChanged("PersonalEmailPrimaryk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<PersonalEmailSecondary>k__BackingField", IsNullable=true, Order=23)]
        public string PersonalEmailSecondaryk__BackingField {
            get {
                return this.personalEmailSecondaryk__BackingFieldField;
            }
            set {
                this.personalEmailSecondaryk__BackingFieldField = value;
                this.RaisePropertyChanged("PersonalEmailSecondaryk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<PersonalHomepage>k__BackingField", IsNullable=true, Order=24)]
        public string PersonalHomepagek__BackingField {
            get {
                return this.personalHomepagek__BackingFieldField;
            }
            set {
                this.personalHomepagek__BackingFieldField = value;
                this.RaisePropertyChanged("PersonalHomepagek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<PersonalInstantMessengerAddresses>k__BackingField", IsNullable=true, Order=25)]
        public InstantMessengerAddresses PersonalInstantMessengerAddressesk__BackingField {
            get {
                return this.personalInstantMessengerAddressesk__BackingFieldField;
            }
            set {
                this.personalInstantMessengerAddressesk__BackingFieldField = value;
                this.RaisePropertyChanged("PersonalInstantMessengerAddressesk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<PersonalPhoneMobile>k__BackingField", IsNullable=true, Order=26)]
        public PhoneNumber PersonalPhoneMobilek__BackingField {
            get {
                return this.personalPhoneMobilek__BackingFieldField;
            }
            set {
                this.personalPhoneMobilek__BackingFieldField = value;
                this.RaisePropertyChanged("PersonalPhoneMobilek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<PictureData>k__BackingField", DataType="base64Binary", IsNullable=true, Order=27)]
        public byte[] PictureDatak__BackingField {
            get {
                return this.pictureDatak__BackingFieldField;
            }
            set {
                this.pictureDatak__BackingFieldField = value;
                this.RaisePropertyChanged("PictureDatak__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<PictureName>k__BackingField", IsNullable=true, Order=28)]
        public string PictureNamek__BackingField {
            get {
                return this.pictureNamek__BackingFieldField;
            }
            set {
                this.pictureNamek__BackingFieldField = value;
                this.RaisePropertyChanged("PictureNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<RelationshipStatus>k__BackingField", Order=29)]
        public RelationshipStatus RelationshipStatusk__BackingField {
            get {
                return this.relationshipStatusk__BackingFieldField;
            }
            set {
                this.relationshipStatusk__BackingFieldField = value;
                this.RaisePropertyChanged("RelationshipStatusk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SourceSpecificAttributes>k__BackingField", IsNullable=true, Order=30)]
        public System.Data.DataSet SourceSpecificAttributesk__BackingField {
            get {
                return this.sourceSpecificAttributesk__BackingFieldField;
            }
            set {
                this.sourceSpecificAttributesk__BackingFieldField = value;
                this.RaisePropertyChanged("SourceSpecificAttributesk__BackingField");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public partial class AddressDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityNamek__BackingFieldField;
        
        private string countryNamek__BackingFieldField;
        
        private PhoneNumber phonek__BackingFieldField;
        
        private string postalCodek__BackingFieldField;
        
        private string roomk__BackingFieldField;
        
        private string stateNamek__BackingFieldField;
        
        private string streetNamek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CityName>k__BackingField", IsNullable=true, Order=0)]
        public string CityNamek__BackingField {
            get {
                return this.cityNamek__BackingFieldField;
            }
            set {
                this.cityNamek__BackingFieldField = value;
                this.RaisePropertyChanged("CityNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CountryName>k__BackingField", IsNullable=true, Order=1)]
        public string CountryNamek__BackingField {
            get {
                return this.countryNamek__BackingFieldField;
            }
            set {
                this.countryNamek__BackingFieldField = value;
                this.RaisePropertyChanged("CountryNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Phone>k__BackingField", IsNullable=true, Order=2)]
        public PhoneNumber Phonek__BackingField {
            get {
                return this.phonek__BackingFieldField;
            }
            set {
                this.phonek__BackingFieldField = value;
                this.RaisePropertyChanged("Phonek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<PostalCode>k__BackingField", IsNullable=true, Order=3)]
        public string PostalCodek__BackingField {
            get {
                return this.postalCodek__BackingFieldField;
            }
            set {
                this.postalCodek__BackingFieldField = value;
                this.RaisePropertyChanged("PostalCodek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Room>k__BackingField", IsNullable=true, Order=4)]
        public string Roomk__BackingField {
            get {
                return this.roomk__BackingFieldField;
            }
            set {
                this.roomk__BackingFieldField = value;
                this.RaisePropertyChanged("Roomk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<StateName>k__BackingField", IsNullable=true, Order=5)]
        public string StateNamek__BackingField {
            get {
                return this.stateNamek__BackingFieldField;
            }
            set {
                this.stateNamek__BackingFieldField = value;
                this.RaisePropertyChanged("StateNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<StreetName>k__BackingField", IsNullable=true, Order=6)]
        public string StreetNamek__BackingField {
            get {
                return this.streetNamek__BackingFieldField;
            }
            set {
                this.streetNamek__BackingFieldField = value;
                this.RaisePropertyChanged("StreetNamek__BackingField");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public partial class PhoneNumber : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int areaCodek__BackingFieldField;
        
        private CountryCode countryCodek__BackingFieldField;
        
        private string numberk__BackingFieldField;
        
        private string denormalizedPhoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<AreaCode>k__BackingField", Order=0)]
        public int AreaCodek__BackingField {
            get {
                return this.areaCodek__BackingFieldField;
            }
            set {
                this.areaCodek__BackingFieldField = value;
                this.RaisePropertyChanged("AreaCodek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CountryCode>k__BackingField", Order=1)]
        public CountryCode CountryCodek__BackingField {
            get {
                return this.countryCodek__BackingFieldField;
            }
            set {
                this.countryCodek__BackingFieldField = value;
                this.RaisePropertyChanged("CountryCodek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Number>k__BackingField", IsNullable=true, Order=2)]
        public string Numberk__BackingField {
            get {
                return this.numberk__BackingFieldField;
            }
            set {
                this.numberk__BackingFieldField = value;
                this.RaisePropertyChanged("Numberk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string denormalizedPhoneNumber {
            get {
                return this.denormalizedPhoneNumberField;
            }
            set {
                this.denormalizedPhoneNumberField = value;
                this.RaisePropertyChanged("denormalizedPhoneNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public enum CountryCode {
        
        /// <remarks/>
        Afghanistan,
        
        /// <remarks/>
        Albania,
        
        /// <remarks/>
        Algeria,
        
        /// <remarks/>
        AmericanSamoa,
        
        /// <remarks/>
        Andorra,
        
        /// <remarks/>
        Angola,
        
        /// <remarks/>
        Anguilla,
        
        /// <remarks/>
        Antarctica,
        
        /// <remarks/>
        Antigua,
        
        /// <remarks/>
        Argentina,
        
        /// <remarks/>
        Armenia,
        
        /// <remarks/>
        Aruba,
        
        /// <remarks/>
        Ascension,
        
        /// <remarks/>
        Australia,
        
        /// <remarks/>
        AustralianExternalTerritories,
        
        /// <remarks/>
        Austria,
        
        /// <remarks/>
        Azerbaijan,
        
        /// <remarks/>
        Bahamas,
        
        /// <remarks/>
        Bahrain,
        
        /// <remarks/>
        Bangladesh,
        
        /// <remarks/>
        Barbados,
        
        /// <remarks/>
        Barbuda,
        
        /// <remarks/>
        Belarus,
        
        /// <remarks/>
        Belgium,
        
        /// <remarks/>
        Belize,
        
        /// <remarks/>
        Benin,
        
        /// <remarks/>
        Bermuda,
        
        /// <remarks/>
        Bhutan,
        
        /// <remarks/>
        Bolivia,
        
        /// <remarks/>
        BosniaHerzegovina,
        
        /// <remarks/>
        Botswana,
        
        /// <remarks/>
        Brazil,
        
        /// <remarks/>
        BritishVirginIslands,
        
        /// <remarks/>
        BruneiDarussalam,
        
        /// <remarks/>
        Bulgaria,
        
        /// <remarks/>
        BurkinaFaso,
        
        /// <remarks/>
        Burundi,
        
        /// <remarks/>
        Cambodia,
        
        /// <remarks/>
        Cameroon,
        
        /// <remarks/>
        CapeVerdeIslands,
        
        /// <remarks/>
        CaymanIslands,
        
        /// <remarks/>
        CentralAfricanRepublic,
        
        /// <remarks/>
        Chad,
        
        /// <remarks/>
        ChathamIslandNewZealand,
        
        /// <remarks/>
        Chile,
        
        /// <remarks/>
        ChinaPRC,
        
        /// <remarks/>
        ChristmasIsland,
        
        /// <remarks/>
        CocosKeelingIslands,
        
        /// <remarks/>
        Colombia,
        
        /// <remarks/>
        Comoros,
        
        /// <remarks/>
        Congo,
        
        /// <remarks/>
        CongoDemRepof,
        
        /// <remarks/>
        CookIslands,
        
        /// <remarks/>
        CostaRica,
        
        /// <remarks/>
        CotedIvoireIvoryCoast,
        
        /// <remarks/>
        Croatia,
        
        /// <remarks/>
        Cuba,
        
        /// <remarks/>
        CubaGuantanamoBay,
        
        /// <remarks/>
        Curacao,
        
        /// <remarks/>
        Cyprus,
        
        /// <remarks/>
        CzechRepublic,
        
        /// <remarks/>
        Denmark,
        
        /// <remarks/>
        DiegoGarcia,
        
        /// <remarks/>
        Djibouti,
        
        /// <remarks/>
        Dominica,
        
        /// <remarks/>
        DominicanRepublic,
        
        /// <remarks/>
        DominicanRepublic2,
        
        /// <remarks/>
        EasterIsland,
        
        /// <remarks/>
        EastTimor,
        
        /// <remarks/>
        Ecuador,
        
        /// <remarks/>
        Egypt,
        
        /// <remarks/>
        EllipsoMobileSatelliteservice,
        
        /// <remarks/>
        ElSalvador,
        
        /// <remarks/>
        EMSATMobileSatelliteservice,
        
        /// <remarks/>
        EquatorialGuinea,
        
        /// <remarks/>
        Eritrea,
        
        /// <remarks/>
        Estonia,
        
        /// <remarks/>
        Ethiopia,
        
        /// <remarks/>
        FalklandIslandsMalvinas,
        
        /// <remarks/>
        FaroeIslands,
        
        /// <remarks/>
        FijiIslands,
        
        /// <remarks/>
        Finland,
        
        /// <remarks/>
        France,
        
        /// <remarks/>
        FrenchAntilles,
        
        /// <remarks/>
        FrenchGuiana,
        
        /// <remarks/>
        FrenchPolynesia,
        
        /// <remarks/>
        GaboneseRepublic,
        
        /// <remarks/>
        Gambia,
        
        /// <remarks/>
        Georgia,
        
        /// <remarks/>
        Germany,
        
        /// <remarks/>
        Ghana,
        
        /// <remarks/>
        Gibraltar,
        
        /// <remarks/>
        GlobalMobileSatelliteSystemGMSS,
        
        /// <remarks/>
        GlobalstarMobileSatelliteService,
        
        /// <remarks/>
        Greece,
        
        /// <remarks/>
        Greenland,
        
        /// <remarks/>
        Grenada,
        
        /// <remarks/>
        Guadeloupe,
        
        /// <remarks/>
        Guam,
        
        /// <remarks/>
        GuantanamoBay,
        
        /// <remarks/>
        Guatemala,
        
        /// <remarks/>
        Guinea,
        
        /// <remarks/>
        GuineaBissau,
        
        /// <remarks/>
        Guyana,
        
        /// <remarks/>
        Haiti,
        
        /// <remarks/>
        Honduras,
        
        /// <remarks/>
        HongKong,
        
        /// <remarks/>
        Hungary,
        
        /// <remarks/>
        Iceland,
        
        /// <remarks/>
        ICOGlobalMobileSatelliteService,
        
        /// <remarks/>
        India,
        
        /// <remarks/>
        Indonesia,
        
        /// <remarks/>
        InmarsatAtlanticOceanEast,
        
        /// <remarks/>
        InmarsatAtlanticOceanWest,
        
        /// <remarks/>
        InmarsatIndianOcean,
        
        /// <remarks/>
        InmarsatPacificOcean,
        
        /// <remarks/>
        InmarsatSNAC,
        
        /// <remarks/>
        InternationalFreephoneService,
        
        /// <remarks/>
        InternationalSharedCostServiceISCS,
        
        /// <remarks/>
        Iran,
        
        /// <remarks/>
        Iraq,
        
        /// <remarks/>
        Ireland,
        
        /// <remarks/>
        IridiumMobileSatelliteservice,
        
        /// <remarks/>
        Israel,
        
        /// <remarks/>
        Italy,
        
        /// <remarks/>
        Jamaica,
        
        /// <remarks/>
        Japan,
        
        /// <remarks/>
        Jordan,
        
        /// <remarks/>
        Kenya,
        
        /// <remarks/>
        Kiribati,
        
        /// <remarks/>
        KoreaNorth,
        
        /// <remarks/>
        KoreaSouth,
        
        /// <remarks/>
        Kuwait,
        
        /// <remarks/>
        KyrgyzRepublic,
        
        /// <remarks/>
        Laos,
        
        /// <remarks/>
        Latvia,
        
        /// <remarks/>
        Lebanon,
        
        /// <remarks/>
        Lesotho,
        
        /// <remarks/>
        Liberia,
        
        /// <remarks/>
        Libya,
        
        /// <remarks/>
        Liechtenstein,
        
        /// <remarks/>
        Lithuania,
        
        /// <remarks/>
        Luxembourg,
        
        /// <remarks/>
        Macao,
        
        /// <remarks/>
        MacedoniaFormerYugoslavRepof,
        
        /// <remarks/>
        Madagascar,
        
        /// <remarks/>
        Malawi,
        
        /// <remarks/>
        Malaysia,
        
        /// <remarks/>
        Maldives,
        
        /// <remarks/>
        MaliRepublic,
        
        /// <remarks/>
        Malta,
        
        /// <remarks/>
        MarshallIslands,
        
        /// <remarks/>
        Martinique,
        
        /// <remarks/>
        Mauritania,
        
        /// <remarks/>
        Mauritius,
        
        /// <remarks/>
        MayotteIsland,
        
        /// <remarks/>
        Mexico,
        
        /// <remarks/>
        MicronesiaFederalStatesOf,
        
        /// <remarks/>
        MidwayIsland,
        
        /// <remarks/>
        Moldova,
        
        /// <remarks/>
        Monaco,
        
        /// <remarks/>
        Mongolia,
        
        /// <remarks/>
        Montenegro,
        
        /// <remarks/>
        Montserrat,
        
        /// <remarks/>
        Morocco,
        
        /// <remarks/>
        Mozambique,
        
        /// <remarks/>
        Myanmar,
        
        /// <remarks/>
        Namibia,
        
        /// <remarks/>
        Nauru,
        
        /// <remarks/>
        Nepal,
        
        /// <remarks/>
        Netherlands,
        
        /// <remarks/>
        NetherlandsAntilles,
        
        /// <remarks/>
        Nevis,
        
        /// <remarks/>
        NewCaledonia,
        
        /// <remarks/>
        NewZealand,
        
        /// <remarks/>
        Nicaragua,
        
        /// <remarks/>
        Niger,
        
        /// <remarks/>
        Nigeria,
        
        /// <remarks/>
        Niue,
        
        /// <remarks/>
        NorfolkIsland,
        
        /// <remarks/>
        NorthernMarianasIslands,
        
        /// <remarks/>
        Norway,
        
        /// <remarks/>
        Oman,
        
        /// <remarks/>
        Pakistan,
        
        /// <remarks/>
        Palau,
        
        /// <remarks/>
        PalestinianSettlements,
        
        /// <remarks/>
        Panama,
        
        /// <remarks/>
        PapuaNewGuinea,
        
        /// <remarks/>
        Paraguay,
        
        /// <remarks/>
        Peru,
        
        /// <remarks/>
        Philippines,
        
        /// <remarks/>
        Poland,
        
        /// <remarks/>
        Portugal,
        
        /// <remarks/>
        PuertoRico,
        
        /// <remarks/>
        PuertoRico2,
        
        /// <remarks/>
        Qatar,
        
        /// <remarks/>
        RéunionIsland,
        
        /// <remarks/>
        Romania,
        
        /// <remarks/>
        RussiaKazakhstan,
        
        /// <remarks/>
        RwandeseRepublic,
        
        /// <remarks/>
        Samoa,
        
        /// <remarks/>
        SanMarino,
        
        /// <remarks/>
        SaoTomeandPrincipe,
        
        /// <remarks/>
        SaudiArabia,
        
        /// <remarks/>
        Senegal,
        
        /// <remarks/>
        Serbia,
        
        /// <remarks/>
        SeychellesRepublic,
        
        /// <remarks/>
        SierraLeone,
        
        /// <remarks/>
        Singapore,
        
        /// <remarks/>
        SlovakRepublic,
        
        /// <remarks/>
        Slovenia,
        
        /// <remarks/>
        SolomonIslands,
        
        /// <remarks/>
        SomaliDemocraticRepublic,
        
        /// <remarks/>
        SouthAfrica,
        
        /// <remarks/>
        Spain,
        
        /// <remarks/>
        SriLanka,
        
        /// <remarks/>
        StHelena,
        
        /// <remarks/>
        StKittsNevis,
        
        /// <remarks/>
        StLucia,
        
        /// <remarks/>
        StPierreMiquelon,
        
        /// <remarks/>
        StVincentGrenadines,
        
        /// <remarks/>
        Sudan,
        
        /// <remarks/>
        Suriname,
        
        /// <remarks/>
        Swaziland,
        
        /// <remarks/>
        Sweden,
        
        /// <remarks/>
        Switzerland,
        
        /// <remarks/>
        Syria,
        
        /// <remarks/>
        Taiwan,
        
        /// <remarks/>
        Tajikistan,
        
        /// <remarks/>
        Tanzania,
        
        /// <remarks/>
        Thailand,
        
        /// <remarks/>
        ThurayaMobileSatelliteservice,
        
        /// <remarks/>
        TimorLeste,
        
        /// <remarks/>
        TogoleseRepublic,
        
        /// <remarks/>
        Tokelau,
        
        /// <remarks/>
        TongaIslands,
        
        /// <remarks/>
        TrinidadTobago,
        
        /// <remarks/>
        Tunisia,
        
        /// <remarks/>
        Turkey,
        
        /// <remarks/>
        Turkmenistan,
        
        /// <remarks/>
        TurksandCaicosIslands,
        
        /// <remarks/>
        Tuvalu,
        
        /// <remarks/>
        Uganda,
        
        /// <remarks/>
        Ukraine,
        
        /// <remarks/>
        UnitedArabEmirates,
        
        /// <remarks/>
        UnitedKingdom,
        
        /// <remarks/>
        UnitedStatesofAmericaCanada,
        
        /// <remarks/>
        UniversalPersonalTelecommunicationsUPT,
        
        /// <remarks/>
        unknown175,
        
        /// <remarks/>
        unspecified,
        
        /// <remarks/>
        Uruguay,
        
        /// <remarks/>
        USVirginIslands,
        
        /// <remarks/>
        Uzbekistan,
        
        /// <remarks/>
        Vanuatu,
        
        /// <remarks/>
        VaticanCity,
        
        /// <remarks/>
        Venezuela,
        
        /// <remarks/>
        Vietnam,
        
        /// <remarks/>
        WakeIsland,
        
        /// <remarks/>
        WallisandFutunaIslands,
        
        /// <remarks/>
        Yemen,
        
        /// <remarks/>
        Zambia,
        
        /// <remarks/>
        Zanzibar,
        
        /// <remarks/>
        Zimbabwe,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public partial class PersonName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string academicTitlek__BackingFieldField;
        
        private string firstNamek__BackingFieldField;
        
        private string formerNamek__BackingFieldField;
        
        private string lastNamePrefixk__BackingFieldField;
        
        private string lastNamek__BackingFieldField;
        
        private string middleNamek__BackingFieldField;
        
        private string suffixk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<AcademicTitle>k__BackingField", IsNullable=true, Order=0)]
        public string AcademicTitlek__BackingField {
            get {
                return this.academicTitlek__BackingFieldField;
            }
            set {
                this.academicTitlek__BackingFieldField = value;
                this.RaisePropertyChanged("AcademicTitlek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<FirstName>k__BackingField", IsNullable=true, Order=1)]
        public string FirstNamek__BackingField {
            get {
                return this.firstNamek__BackingFieldField;
            }
            set {
                this.firstNamek__BackingFieldField = value;
                this.RaisePropertyChanged("FirstNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<FormerName>k__BackingField", IsNullable=true, Order=2)]
        public string FormerNamek__BackingField {
            get {
                return this.formerNamek__BackingFieldField;
            }
            set {
                this.formerNamek__BackingFieldField = value;
                this.RaisePropertyChanged("FormerNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<LastNamePrefix>k__BackingField", IsNullable=true, Order=3)]
        public string LastNamePrefixk__BackingField {
            get {
                return this.lastNamePrefixk__BackingFieldField;
            }
            set {
                this.lastNamePrefixk__BackingFieldField = value;
                this.RaisePropertyChanged("LastNamePrefixk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<LastName>k__BackingField", IsNullable=true, Order=4)]
        public string LastNamek__BackingField {
            get {
                return this.lastNamek__BackingFieldField;
            }
            set {
                this.lastNamek__BackingFieldField = value;
                this.RaisePropertyChanged("LastNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<MiddleName>k__BackingField", IsNullable=true, Order=5)]
        public string MiddleNamek__BackingField {
            get {
                return this.middleNamek__BackingFieldField;
            }
            set {
                this.middleNamek__BackingFieldField = value;
                this.RaisePropertyChanged("MiddleNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Suffix>k__BackingField", IsNullable=true, Order=6)]
        public string Suffixk__BackingField {
            get {
                return this.suffixk__BackingFieldField;
            }
            set {
                this.suffixk__BackingFieldField = value;
                this.RaisePropertyChanged("Suffixk__BackingField");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public partial class LanguageKnowledge : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string languageNameField;
        
        private KnowledgeLevel levelField;
        
        private bool levelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string LanguageName {
            get {
                return this.languageNameField;
            }
            set {
                this.languageNameField = value;
                this.RaisePropertyChanged("LanguageName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public KnowledgeLevel Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LevelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
                this.RaisePropertyChanged("LevelSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public enum KnowledgeLevel {
        
        /// <remarks/>
        unknown,
        
        /// <remarks/>
        Beginner,
        
        /// <remarks/>
        Intermediate,
        
        /// <remarks/>
        Professional,
        
        /// <remarks/>
        Expert,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public partial class ImageEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] imageDataField;
        
        private string imageNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] ImageData {
            get {
                return this.imageDataField;
            }
            set {
                this.imageDataField = value;
                this.RaisePropertyChanged("ImageData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ImageName {
            get {
                return this.imageNameField;
            }
            set {
                this.imageNameField = value;
                this.RaisePropertyChanged("ImageName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public partial class ContactReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isBusinessContactField;
        
        private bool isBusinessContactFieldSpecified;
        
        private bool isPrivateContactField;
        
        private bool isPrivateContactFieldSpecified;
        
        private string targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsBusinessContact {
            get {
                return this.isBusinessContactField;
            }
            set {
                this.isBusinessContactField = value;
                this.RaisePropertyChanged("IsBusinessContact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsBusinessContactSpecified {
            get {
                return this.isBusinessContactFieldSpecified;
            }
            set {
                this.isBusinessContactFieldSpecified = value;
                this.RaisePropertyChanged("IsBusinessContactSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsPrivateContact {
            get {
                return this.isPrivateContactField;
            }
            set {
                this.isPrivateContactField = value;
                this.RaisePropertyChanged("IsPrivateContact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPrivateContactSpecified {
            get {
                return this.isPrivateContactFieldSpecified;
            }
            set {
                this.isPrivateContactFieldSpecified = value;
                this.RaisePropertyChanged("IsPrivateContactSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("Target");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public partial class InstantMessengerAddresses : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string googleTalkk__BackingFieldField;
        
        private string icqk__BackingFieldField;
        
        private string msnMessengerk__BackingFieldField;
        
        private string skypek__BackingFieldField;
        
        private string yahooMessengerk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<GoogleTalk>k__BackingField", IsNullable=true, Order=0)]
        public string GoogleTalkk__BackingField {
            get {
                return this.googleTalkk__BackingFieldField;
            }
            set {
                this.googleTalkk__BackingFieldField = value;
                this.RaisePropertyChanged("GoogleTalkk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Icq>k__BackingField", IsNullable=true, Order=1)]
        public string Icqk__BackingField {
            get {
                return this.icqk__BackingFieldField;
            }
            set {
                this.icqk__BackingFieldField = value;
                this.RaisePropertyChanged("Icqk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<MsnMessenger>k__BackingField", IsNullable=true, Order=2)]
        public string MsnMessengerk__BackingField {
            get {
                return this.msnMessengerk__BackingFieldField;
            }
            set {
                this.msnMessengerk__BackingFieldField = value;
                this.RaisePropertyChanged("MsnMessengerk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Skype>k__BackingField", IsNullable=true, Order=3)]
        public string Skypek__BackingField {
            get {
                return this.skypek__BackingFieldField;
            }
            set {
                this.skypek__BackingFieldField = value;
                this.RaisePropertyChanged("Skypek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<YahooMessenger>k__BackingField", IsNullable=true, Order=4)]
        public string YahooMessengerk__BackingField {
            get {
                return this.yahooMessengerk__BackingFieldField;
            }
            set {
                this.yahooMessengerk__BackingFieldField = value;
                this.RaisePropertyChanged("YahooMessengerk__BackingField");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public partial class BusinessHistoryEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string businessCompanyNameField;
        
        private string businessDepartmentField;
        
        private string businessPositionField;
        
        private System.DateTime endField;
        
        private bool endFieldSpecified;
        
        private System.DateTime startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string BusinessCompanyName {
            get {
                return this.businessCompanyNameField;
            }
            set {
                this.businessCompanyNameField = value;
                this.RaisePropertyChanged("BusinessCompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string BusinessDepartment {
            get {
                return this.businessDepartmentField;
            }
            set {
                this.businessDepartmentField = value;
                this.RaisePropertyChanged("BusinessDepartment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string BusinessPosition {
            get {
                return this.businessPositionField;
            }
            set {
                this.businessPositionField = value;
                this.RaisePropertyChanged("BusinessPosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("End");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndSpecified {
            get {
                return this.endFieldSpecified;
            }
            set {
                this.endFieldSpecified = value;
                this.RaisePropertyChanged("EndSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("Start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("StartSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public partial class BusinessCertificate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string certificateNameField;
        
        private System.DateTime certificationDateField;
        
        private bool certificationDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CertificateName {
            get {
                return this.certificateNameField;
            }
            set {
                this.certificateNameField = value;
                this.RaisePropertyChanged("CertificateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CertificationDate {
            get {
                return this.certificationDateField;
            }
            set {
                this.certificationDateField = value;
                this.RaisePropertyChanged("CertificationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CertificationDateSpecified {
            get {
                return this.certificationDateFieldSpecified;
            }
            set {
                this.certificationDateFieldSpecified = value;
                this.RaisePropertyChanged("CertificationDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public partial class SyncData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateOfCreationk__BackingFieldField;
        
        private System.DateTime dateOfLastChangek__BackingFieldField;
        
        private bool deletedk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DateOfCreation>k__BackingField", Order=0)]
        public System.DateTime DateOfCreationk__BackingField {
            get {
                return this.dateOfCreationk__BackingFieldField;
            }
            set {
                this.dateOfCreationk__BackingFieldField = value;
                this.RaisePropertyChanged("DateOfCreationk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DateOfLastChange>k__BackingField", Order=1)]
        public System.DateTime DateOfLastChangek__BackingField {
            get {
                return this.dateOfLastChangek__BackingFieldField;
            }
            set {
                this.dateOfLastChangek__BackingFieldField = value;
                this.RaisePropertyChanged("DateOfLastChangek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Deleted>k__BackingField", Order=2)]
        public bool Deletedk__BackingField {
            get {
                return this.deletedk__BackingFieldField;
            }
            set {
                this.deletedk__BackingFieldField = value;
                this.RaisePropertyChanged("Deletedk__BackingField");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StdContact))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase")]
    public partial class StdElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SyncData internalSyncDatak__BackingFieldField;
        
        private System.Data.DataSet externalIdentifierField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<InternalSyncData>k__BackingField", IsNullable=true, Order=0)]
        public SyncData InternalSyncDatak__BackingField {
            get {
                return this.internalSyncDatak__BackingFieldField;
            }
            set {
                this.internalSyncDatak__BackingFieldField = value;
                this.RaisePropertyChanged("InternalSyncDatak__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Data.DataSet externalIdentifier {
            get {
                return this.externalIdentifierField;
            }
            set {
                this.externalIdentifierField = value;
                this.RaisePropertyChanged("externalIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public enum Gender {
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        Male,
        
        /// <remarks/>
        Female,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public enum RelationshipStatus {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        Searching,
        
        /// <remarks/>
        InARelationship,
        
        /// <remarks/>
        Engaged,
        
        /// <remarks/>
        Married,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAll", WrapperNamespace="http://svenerikmatzen.com/Sem/Sync/OnlineStorage", IsWrapped=true)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svenerikmatzen.com/Sem/Sync/OnlineStorage", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientFolderName;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(string clientFolderName) {
            this.clientFolderName = clientFolderName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllResponse", WrapperNamespace="http://svenerikmatzen.com/Sem/Sync/OnlineStorage", IsWrapped=true)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svenerikmatzen.com/Sem/Sync/OnlineStorage", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Sem.Sync.Connector.OnlineStorage.ContactService2.ContactListContainer GetAllResult;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(Sem.Sync.Connector.OnlineStorage.ContactService2.ContactListContainer GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WriteFullList", WrapperNamespace="http://svenerikmatzen.com/Sem/Sync/OnlineStorage", IsWrapped=true)]
    public partial class WriteFullListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svenerikmatzen.com/Sem/Sync/OnlineStorage", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Sem.Sync.Connector.OnlineStorage.ContactService2.ContactListContainer elements;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svenerikmatzen.com/Sem/Sync/OnlineStorage", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientFolderName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svenerikmatzen.com/Sem/Sync/OnlineStorage", Order=2)]
        public bool skipIfExisting;
        
        public WriteFullListRequest() {
        }
        
        public WriteFullListRequest(Sem.Sync.Connector.OnlineStorage.ContactService2.ContactListContainer elements, string clientFolderName, bool skipIfExisting) {
            this.elements = elements;
            this.clientFolderName = clientFolderName;
            this.skipIfExisting = skipIfExisting;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WriteFullListResponse", WrapperNamespace="http://svenerikmatzen.com/Sem/Sync/OnlineStorage", IsWrapped=true)]
    public partial class WriteFullListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svenerikmatzen.com/Sem/Sync/OnlineStorage", Order=0)]
        public bool WriteFullListResult;
        
        public WriteFullListResponse() {
        }
        
        public WriteFullListResponse(bool WriteFullListResult) {
            this.WriteFullListResult = WriteFullListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactServiceChannel : Sem.Sync.Connector.OnlineStorage.ContactService2.IContactService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactServiceClient : System.ServiceModel.ClientBase<Sem.Sync.Connector.OnlineStorage.ContactService2.IContactService>, Sem.Sync.Connector.OnlineStorage.ContactService2.IContactService {
        
        public ContactServiceClient() {
        }
        
        public ContactServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sem.Sync.Connector.OnlineStorage.ContactService2.GetAllResponse Sem.Sync.Connector.OnlineStorage.ContactService2.IContactService.GetAll(Sem.Sync.Connector.OnlineStorage.ContactService2.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public Sem.Sync.Connector.OnlineStorage.ContactService2.ContactListContainer GetAll(string clientFolderName) {
            Sem.Sync.Connector.OnlineStorage.ContactService2.GetAllRequest inValue = new Sem.Sync.Connector.OnlineStorage.ContactService2.GetAllRequest();
            inValue.clientFolderName = clientFolderName;
            Sem.Sync.Connector.OnlineStorage.ContactService2.GetAllResponse retVal = ((Sem.Sync.Connector.OnlineStorage.ContactService2.IContactService)(this)).GetAll(inValue);
            return retVal.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sem.Sync.Connector.OnlineStorage.ContactService2.WriteFullListResponse Sem.Sync.Connector.OnlineStorage.ContactService2.IContactService.WriteFullList(Sem.Sync.Connector.OnlineStorage.ContactService2.WriteFullListRequest request) {
            return base.Channel.WriteFullList(request);
        }
        
        public bool WriteFullList(Sem.Sync.Connector.OnlineStorage.ContactService2.ContactListContainer elements, string clientFolderName, bool skipIfExisting) {
            Sem.Sync.Connector.OnlineStorage.ContactService2.WriteFullListRequest inValue = new Sem.Sync.Connector.OnlineStorage.ContactService2.WriteFullListRequest();
            inValue.elements = elements;
            inValue.clientFolderName = clientFolderName;
            inValue.skipIfExisting = skipIfExisting;
            Sem.Sync.Connector.OnlineStorage.ContactService2.WriteFullListResponse retVal = ((Sem.Sync.Connector.OnlineStorage.ContactService2.IContactService)(this)).WriteFullList(inValue);
            return retVal.WriteFullListResult;
        }
    }
}
