//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem.GenericHelpers.ExceptionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.svenerikmatzen.info/Sem.GenericHelpers.ExceptionService", ConfigurationName="ExceptionService.IExceptionService")]
    public interface IExceptionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.svenerikmatzen.info/Sem.GenericHelpers.ExceptionService/IExceptionServ" +
            "ice/WriteExceptionData", ReplyAction="http://www.svenerikmatzen.info/Sem.GenericHelpers.ExceptionService/IExceptionServ" +
            "ice/WriteExceptionDataResponse")]
        bool WriteExceptionData(string exceptionData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.svenerikmatzen.info/Sem.GenericHelpers.ExceptionService/IExceptionServ" +
            "ice/GetEncryptionKey", ReplyAction="http://www.svenerikmatzen.info/Sem.GenericHelpers.ExceptionService/IExceptionServ" +
            "ice/GetEncryptionKeyResponse")]
        string GetEncryptionKey();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExceptionServiceChannel : Sem.GenericHelpers.ExceptionService.IExceptionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExceptionServiceClient : System.ServiceModel.ClientBase<Sem.GenericHelpers.ExceptionService.IExceptionService>, Sem.GenericHelpers.ExceptionService.IExceptionService {
        
        public ExceptionServiceClient() {
        }
        
        public ExceptionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExceptionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExceptionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExceptionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool WriteExceptionData(string exceptionData) {
            return base.Channel.WriteExceptionData(exceptionData);
        }
        
        public string GetEncryptionKey() {
            return base.Channel.GetEncryptionKey();
        }
    }
}
