//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem.Sync.Connector.OnlineStorage.OnlineStorage {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactListContainer", Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.OnlineStorage")]
    [System.SerializableAttribute()]
    public partial class ContactListContainer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.StdContact[] ContactListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.StdContact[] ContactList {
            get {
                return this.ContactListField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactListField, value) != true)) {
                    this.ContactListField = value;
                    this.RaisePropertyChanged("ContactList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StdContact", Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase")]
    [System.SerializableAttribute()]
    public partial class StdContact : Sem.Sync.Connector.OnlineStorage.OnlineStorage.StdElement {
        
        private string AdditionalTextDatak__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.AddressDetail BusinessAddressPrimaryk__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.AddressDetail BusinessAddressSecondaryk__BackingFieldField;
        
        private string BusinessCompanyNamek__BackingFieldField;
        
        private string BusinessDepartmentk__BackingFieldField;
        
        private string BusinessEmailPrimaryk__BackingFieldField;
        
        private string BusinessEmailSecondaryk__BackingFieldField;
        
        private string BusinessHomepagek__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.InstantMessengerAddresses BusinessInstantMessengerAddressesk__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.PhoneNumber BusinessPhoneMobilek__BackingFieldField;
        
        private string BusinessPositionk__BackingFieldField;
        
        private string[] Categoriesk__BackingFieldField;
        
        private System.DateTime DateOfBirthk__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.PersonName Namek__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.Gender PersonGenderk__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.AddressDetail PersonalAddressPrimaryk__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.AddressDetail PersonalAddressSecondaryk__BackingFieldField;
        
        private string PersonalEmailPrimaryk__BackingFieldField;
        
        private string PersonalEmailSecondaryk__BackingFieldField;
        
        private string PersonalHomepagek__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.InstantMessengerAddresses PersonalInstantMessengerAddressesk__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.PhoneNumber PersonalPhoneMobilek__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.ProfileIdentifiers PersonalProfileIdentifiersk__BackingFieldField;
        
        private byte[] PictureDatak__BackingFieldField;
        
        private string PictureNamek__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AdditionalTextData>k__BackingField", IsRequired=true)]
        public string AdditionalTextDatak__BackingField {
            get {
                return this.AdditionalTextDatak__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalTextDatak__BackingFieldField, value) != true)) {
                    this.AdditionalTextDatak__BackingFieldField = value;
                    this.RaisePropertyChanged("AdditionalTextDatak__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BusinessAddressPrimary>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.AddressDetail BusinessAddressPrimaryk__BackingField {
            get {
                return this.BusinessAddressPrimaryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessAddressPrimaryk__BackingFieldField, value) != true)) {
                    this.BusinessAddressPrimaryk__BackingFieldField = value;
                    this.RaisePropertyChanged("BusinessAddressPrimaryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BusinessAddressSecondary>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.AddressDetail BusinessAddressSecondaryk__BackingField {
            get {
                return this.BusinessAddressSecondaryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessAddressSecondaryk__BackingFieldField, value) != true)) {
                    this.BusinessAddressSecondaryk__BackingFieldField = value;
                    this.RaisePropertyChanged("BusinessAddressSecondaryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BusinessCompanyName>k__BackingField", IsRequired=true)]
        public string BusinessCompanyNamek__BackingField {
            get {
                return this.BusinessCompanyNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessCompanyNamek__BackingFieldField, value) != true)) {
                    this.BusinessCompanyNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("BusinessCompanyNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BusinessDepartment>k__BackingField", IsRequired=true)]
        public string BusinessDepartmentk__BackingField {
            get {
                return this.BusinessDepartmentk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessDepartmentk__BackingFieldField, value) != true)) {
                    this.BusinessDepartmentk__BackingFieldField = value;
                    this.RaisePropertyChanged("BusinessDepartmentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BusinessEmailPrimary>k__BackingField", IsRequired=true)]
        public string BusinessEmailPrimaryk__BackingField {
            get {
                return this.BusinessEmailPrimaryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessEmailPrimaryk__BackingFieldField, value) != true)) {
                    this.BusinessEmailPrimaryk__BackingFieldField = value;
                    this.RaisePropertyChanged("BusinessEmailPrimaryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BusinessEmailSecondary>k__BackingField", IsRequired=true)]
        public string BusinessEmailSecondaryk__BackingField {
            get {
                return this.BusinessEmailSecondaryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessEmailSecondaryk__BackingFieldField, value) != true)) {
                    this.BusinessEmailSecondaryk__BackingFieldField = value;
                    this.RaisePropertyChanged("BusinessEmailSecondaryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BusinessHomepage>k__BackingField", IsRequired=true)]
        public string BusinessHomepagek__BackingField {
            get {
                return this.BusinessHomepagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessHomepagek__BackingFieldField, value) != true)) {
                    this.BusinessHomepagek__BackingFieldField = value;
                    this.RaisePropertyChanged("BusinessHomepagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BusinessInstantMessengerAddresses>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.InstantMessengerAddresses BusinessInstantMessengerAddressesk__BackingField {
            get {
                return this.BusinessInstantMessengerAddressesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessInstantMessengerAddressesk__BackingFieldField, value) != true)) {
                    this.BusinessInstantMessengerAddressesk__BackingFieldField = value;
                    this.RaisePropertyChanged("BusinessInstantMessengerAddressesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BusinessPhoneMobile>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.PhoneNumber BusinessPhoneMobilek__BackingField {
            get {
                return this.BusinessPhoneMobilek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessPhoneMobilek__BackingFieldField, value) != true)) {
                    this.BusinessPhoneMobilek__BackingFieldField = value;
                    this.RaisePropertyChanged("BusinessPhoneMobilek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BusinessPosition>k__BackingField", IsRequired=true)]
        public string BusinessPositionk__BackingField {
            get {
                return this.BusinessPositionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessPositionk__BackingFieldField, value) != true)) {
                    this.BusinessPositionk__BackingFieldField = value;
                    this.RaisePropertyChanged("BusinessPositionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Categories>k__BackingField", IsRequired=true)]
        public string[] Categoriesk__BackingField {
            get {
                return this.Categoriesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Categoriesk__BackingFieldField, value) != true)) {
                    this.Categoriesk__BackingFieldField = value;
                    this.RaisePropertyChanged("Categoriesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DateOfBirth>k__BackingField", IsRequired=true)]
        public System.DateTime DateOfBirthk__BackingField {
            get {
                return this.DateOfBirthk__BackingFieldField;
            }
            set {
                if ((this.DateOfBirthk__BackingFieldField.Equals(value) != true)) {
                    this.DateOfBirthk__BackingFieldField = value;
                    this.RaisePropertyChanged("DateOfBirthk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.PersonName Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PersonGender>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.Gender PersonGenderk__BackingField {
            get {
                return this.PersonGenderk__BackingFieldField;
            }
            set {
                if ((this.PersonGenderk__BackingFieldField.Equals(value) != true)) {
                    this.PersonGenderk__BackingFieldField = value;
                    this.RaisePropertyChanged("PersonGenderk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PersonalAddressPrimary>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.AddressDetail PersonalAddressPrimaryk__BackingField {
            get {
                return this.PersonalAddressPrimaryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalAddressPrimaryk__BackingFieldField, value) != true)) {
                    this.PersonalAddressPrimaryk__BackingFieldField = value;
                    this.RaisePropertyChanged("PersonalAddressPrimaryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PersonalAddressSecondary>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.AddressDetail PersonalAddressSecondaryk__BackingField {
            get {
                return this.PersonalAddressSecondaryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalAddressSecondaryk__BackingFieldField, value) != true)) {
                    this.PersonalAddressSecondaryk__BackingFieldField = value;
                    this.RaisePropertyChanged("PersonalAddressSecondaryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PersonalEmailPrimary>k__BackingField", IsRequired=true)]
        public string PersonalEmailPrimaryk__BackingField {
            get {
                return this.PersonalEmailPrimaryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalEmailPrimaryk__BackingFieldField, value) != true)) {
                    this.PersonalEmailPrimaryk__BackingFieldField = value;
                    this.RaisePropertyChanged("PersonalEmailPrimaryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PersonalEmailSecondary>k__BackingField", IsRequired=true)]
        public string PersonalEmailSecondaryk__BackingField {
            get {
                return this.PersonalEmailSecondaryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalEmailSecondaryk__BackingFieldField, value) != true)) {
                    this.PersonalEmailSecondaryk__BackingFieldField = value;
                    this.RaisePropertyChanged("PersonalEmailSecondaryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PersonalHomepage>k__BackingField", IsRequired=true)]
        public string PersonalHomepagek__BackingField {
            get {
                return this.PersonalHomepagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalHomepagek__BackingFieldField, value) != true)) {
                    this.PersonalHomepagek__BackingFieldField = value;
                    this.RaisePropertyChanged("PersonalHomepagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PersonalInstantMessengerAddresses>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.InstantMessengerAddresses PersonalInstantMessengerAddressesk__BackingField {
            get {
                return this.PersonalInstantMessengerAddressesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalInstantMessengerAddressesk__BackingFieldField, value) != true)) {
                    this.PersonalInstantMessengerAddressesk__BackingFieldField = value;
                    this.RaisePropertyChanged("PersonalInstantMessengerAddressesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PersonalPhoneMobile>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.PhoneNumber PersonalPhoneMobilek__BackingField {
            get {
                return this.PersonalPhoneMobilek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalPhoneMobilek__BackingFieldField, value) != true)) {
                    this.PersonalPhoneMobilek__BackingFieldField = value;
                    this.RaisePropertyChanged("PersonalPhoneMobilek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PersonalProfileIdentifiers>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.ProfileIdentifiers PersonalProfileIdentifiersk__BackingField {
            get {
                return this.PersonalProfileIdentifiersk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalProfileIdentifiersk__BackingFieldField, value) != true)) {
                    this.PersonalProfileIdentifiersk__BackingFieldField = value;
                    this.RaisePropertyChanged("PersonalProfileIdentifiersk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PictureData>k__BackingField", IsRequired=true)]
        public byte[] PictureDatak__BackingField {
            get {
                return this.PictureDatak__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureDatak__BackingFieldField, value) != true)) {
                    this.PictureDatak__BackingFieldField = value;
                    this.RaisePropertyChanged("PictureDatak__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PictureName>k__BackingField", IsRequired=true)]
        public string PictureNamek__BackingField {
            get {
                return this.PictureNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureNamek__BackingFieldField, value) != true)) {
                    this.PictureNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("PictureNamek__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StdElement", Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sem.Sync.Connector.OnlineStorage.OnlineStorage.StdContact))]
    public partial class StdElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid Idk__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.SyncData InternalSyncDatak__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public System.Guid Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((this.Idk__BackingFieldField.Equals(value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<InternalSyncData>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.SyncData InternalSyncDatak__BackingField {
            get {
                return this.InternalSyncDatak__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.InternalSyncDatak__BackingFieldField, value) != true)) {
                    this.InternalSyncDatak__BackingFieldField = value;
                    this.RaisePropertyChanged("InternalSyncDatak__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyncData", Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    [System.SerializableAttribute()]
    public partial class SyncData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateOfCreationk__BackingFieldField;
        
        private System.DateTime DateOfLastChangek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DateOfCreation>k__BackingField", IsRequired=true)]
        public System.DateTime DateOfCreationk__BackingField {
            get {
                return this.DateOfCreationk__BackingFieldField;
            }
            set {
                if ((this.DateOfCreationk__BackingFieldField.Equals(value) != true)) {
                    this.DateOfCreationk__BackingFieldField = value;
                    this.RaisePropertyChanged("DateOfCreationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DateOfLastChange>k__BackingField", IsRequired=true)]
        public System.DateTime DateOfLastChangek__BackingField {
            get {
                return this.DateOfLastChangek__BackingFieldField;
            }
            set {
                if ((this.DateOfLastChangek__BackingFieldField.Equals(value) != true)) {
                    this.DateOfLastChangek__BackingFieldField = value;
                    this.RaisePropertyChanged("DateOfLastChangek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDetail", Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    [System.SerializableAttribute()]
    public partial class AddressDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CityNamek__BackingFieldField;
        
        private string CountryNamek__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.PhoneNumber Phonek__BackingFieldField;
        
        private string PostalCodek__BackingFieldField;
        
        private string Roomk__BackingFieldField;
        
        private string StateNamek__BackingFieldField;
        
        private string StreetNamek__BackingFieldField;
        
        private string StreetNumberExtensionk__BackingFieldField;
        
        private int StreetNumberk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CityName>k__BackingField", IsRequired=true)]
        public string CityNamek__BackingField {
            get {
                return this.CityNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNamek__BackingFieldField, value) != true)) {
                    this.CityNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("CityNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CountryName>k__BackingField", IsRequired=true)]
        public string CountryNamek__BackingField {
            get {
                return this.CountryNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNamek__BackingFieldField, value) != true)) {
                    this.CountryNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("CountryNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Phone>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.PhoneNumber Phonek__BackingField {
            get {
                return this.Phonek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Phonek__BackingFieldField, value) != true)) {
                    this.Phonek__BackingFieldField = value;
                    this.RaisePropertyChanged("Phonek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PostalCode>k__BackingField", IsRequired=true)]
        public string PostalCodek__BackingField {
            get {
                return this.PostalCodek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodek__BackingFieldField, value) != true)) {
                    this.PostalCodek__BackingFieldField = value;
                    this.RaisePropertyChanged("PostalCodek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Room>k__BackingField", IsRequired=true)]
        public string Roomk__BackingField {
            get {
                return this.Roomk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Roomk__BackingFieldField, value) != true)) {
                    this.Roomk__BackingFieldField = value;
                    this.RaisePropertyChanged("Roomk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<StateName>k__BackingField", IsRequired=true)]
        public string StateNamek__BackingField {
            get {
                return this.StateNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNamek__BackingFieldField, value) != true)) {
                    this.StateNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("StateNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<StreetName>k__BackingField", IsRequired=true)]
        public string StreetNamek__BackingField {
            get {
                return this.StreetNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNamek__BackingFieldField, value) != true)) {
                    this.StreetNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("StreetNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<StreetNumberExtension>k__BackingField", IsRequired=true)]
        public string StreetNumberExtensionk__BackingField {
            get {
                return this.StreetNumberExtensionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNumberExtensionk__BackingFieldField, value) != true)) {
                    this.StreetNumberExtensionk__BackingFieldField = value;
                    this.RaisePropertyChanged("StreetNumberExtensionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<StreetNumber>k__BackingField", IsRequired=true)]
        public int StreetNumberk__BackingField {
            get {
                return this.StreetNumberk__BackingFieldField;
            }
            set {
                if ((this.StreetNumberk__BackingFieldField.Equals(value) != true)) {
                    this.StreetNumberk__BackingFieldField = value;
                    this.RaisePropertyChanged("StreetNumberk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstantMessengerAddresses", Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    [System.SerializableAttribute()]
    public partial class InstantMessengerAddresses : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string GoogleTalkk__BackingFieldField;
        
        private string ICQk__BackingFieldField;
        
        private string MsnMessengerk__BackingFieldField;
        
        private string Skypek__BackingFieldField;
        
        private string YahooMessengerk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<GoogleTalk>k__BackingField", IsRequired=true)]
        public string GoogleTalkk__BackingField {
            get {
                return this.GoogleTalkk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.GoogleTalkk__BackingFieldField, value) != true)) {
                    this.GoogleTalkk__BackingFieldField = value;
                    this.RaisePropertyChanged("GoogleTalkk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ICQ>k__BackingField", IsRequired=true)]
        public string ICQk__BackingField {
            get {
                return this.ICQk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ICQk__BackingFieldField, value) != true)) {
                    this.ICQk__BackingFieldField = value;
                    this.RaisePropertyChanged("ICQk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MsnMessenger>k__BackingField", IsRequired=true)]
        public string MsnMessengerk__BackingField {
            get {
                return this.MsnMessengerk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MsnMessengerk__BackingFieldField, value) != true)) {
                    this.MsnMessengerk__BackingFieldField = value;
                    this.RaisePropertyChanged("MsnMessengerk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Skype>k__BackingField", IsRequired=true)]
        public string Skypek__BackingField {
            get {
                return this.Skypek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Skypek__BackingFieldField, value) != true)) {
                    this.Skypek__BackingFieldField = value;
                    this.RaisePropertyChanged("Skypek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<YahooMessenger>k__BackingField", IsRequired=true)]
        public string YahooMessengerk__BackingField {
            get {
                return this.YahooMessengerk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.YahooMessengerk__BackingFieldField, value) != true)) {
                    this.YahooMessengerk__BackingFieldField = value;
                    this.RaisePropertyChanged("YahooMessengerk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneNumber", Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    [System.SerializableAttribute()]
    public partial class PhoneNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AreaCodek__BackingFieldField;
        
        private Sem.Sync.Connector.OnlineStorage.OnlineStorage.CountryCode CountryCodek__BackingFieldField;
        
        private string Numberk__BackingFieldField;
        
        private string denormalizedPhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AreaCode>k__BackingField", IsRequired=true)]
        public int AreaCodek__BackingField {
            get {
                return this.AreaCodek__BackingFieldField;
            }
            set {
                if ((this.AreaCodek__BackingFieldField.Equals(value) != true)) {
                    this.AreaCodek__BackingFieldField = value;
                    this.RaisePropertyChanged("AreaCodek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CountryCode>k__BackingField", IsRequired=true)]
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.CountryCode CountryCodek__BackingField {
            get {
                return this.CountryCodek__BackingFieldField;
            }
            set {
                if ((this.CountryCodek__BackingFieldField.Equals(value) != true)) {
                    this.CountryCodek__BackingFieldField = value;
                    this.RaisePropertyChanged("CountryCodek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Number>k__BackingField", IsRequired=true)]
        public string Numberk__BackingField {
            get {
                return this.Numberk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Numberk__BackingFieldField, value) != true)) {
                    this.Numberk__BackingFieldField = value;
                    this.RaisePropertyChanged("Numberk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string denormalizedPhoneNumber {
            get {
                return this.denormalizedPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.denormalizedPhoneNumberField, value) != true)) {
                    this.denormalizedPhoneNumberField = value;
                    this.RaisePropertyChanged("denormalizedPhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonName", Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    [System.SerializableAttribute()]
    public partial class PersonName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AcademicTitlek__BackingFieldField;
        
        private string FirstNamek__BackingFieldField;
        
        private string FormerNamek__BackingFieldField;
        
        private string LastNamePrefixk__BackingFieldField;
        
        private string LastNamek__BackingFieldField;
        
        private string MiddleNamek__BackingFieldField;
        
        private string Suffixk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AcademicTitle>k__BackingField", IsRequired=true)]
        public string AcademicTitlek__BackingField {
            get {
                return this.AcademicTitlek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.AcademicTitlek__BackingFieldField, value) != true)) {
                    this.AcademicTitlek__BackingFieldField = value;
                    this.RaisePropertyChanged("AcademicTitlek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FirstName>k__BackingField", IsRequired=true)]
        public string FirstNamek__BackingField {
            get {
                return this.FirstNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNamek__BackingFieldField, value) != true)) {
                    this.FirstNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("FirstNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FormerName>k__BackingField", IsRequired=true)]
        public string FormerNamek__BackingField {
            get {
                return this.FormerNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FormerNamek__BackingFieldField, value) != true)) {
                    this.FormerNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("FormerNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LastNamePrefix>k__BackingField", IsRequired=true)]
        public string LastNamePrefixk__BackingField {
            get {
                return this.LastNamePrefixk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNamePrefixk__BackingFieldField, value) != true)) {
                    this.LastNamePrefixk__BackingFieldField = value;
                    this.RaisePropertyChanged("LastNamePrefixk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LastName>k__BackingField", IsRequired=true)]
        public string LastNamek__BackingField {
            get {
                return this.LastNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNamek__BackingFieldField, value) != true)) {
                    this.LastNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("LastNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MiddleName>k__BackingField", IsRequired=true)]
        public string MiddleNamek__BackingField {
            get {
                return this.MiddleNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNamek__BackingFieldField, value) != true)) {
                    this.MiddleNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("MiddleNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Suffix>k__BackingField", IsRequired=true)]
        public string Suffixk__BackingField {
            get {
                return this.Suffixk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Suffixk__BackingFieldField, value) != true)) {
                    this.Suffixk__BackingFieldField = value;
                    this.RaisePropertyChanged("Suffixk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileIdentifiers", Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    [System.SerializableAttribute()]
    public partial class ProfileIdentifiers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ActiveDirectoryIdk__BackingFieldField;
        
        private string DefaultProfileIdk__BackingFieldField;
        
        private string FacebookProfileIdk__BackingFieldField;
        
        private string GoogleIdk__BackingFieldField;
        
        private string MeinVZPersonIdk__BackingFieldField;
        
        private string StayFriendsPersonIdk__BackingFieldField;
        
        private string WerKenntWenUrlk__BackingFieldField;
        
        private string XingProfileIdk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ActiveDirectoryId>k__BackingField", IsRequired=true)]
        public string ActiveDirectoryIdk__BackingField {
            get {
                return this.ActiveDirectoryIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveDirectoryIdk__BackingFieldField, value) != true)) {
                    this.ActiveDirectoryIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ActiveDirectoryIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DefaultProfileId>k__BackingField", IsRequired=true)]
        public string DefaultProfileIdk__BackingField {
            get {
                return this.DefaultProfileIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultProfileIdk__BackingFieldField, value) != true)) {
                    this.DefaultProfileIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("DefaultProfileIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FacebookProfileId>k__BackingField", IsRequired=true)]
        public string FacebookProfileIdk__BackingField {
            get {
                return this.FacebookProfileIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookProfileIdk__BackingFieldField, value) != true)) {
                    this.FacebookProfileIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("FacebookProfileIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<GoogleId>k__BackingField", IsRequired=true)]
        public string GoogleIdk__BackingField {
            get {
                return this.GoogleIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.GoogleIdk__BackingFieldField, value) != true)) {
                    this.GoogleIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("GoogleIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MeinVZPersonId>k__BackingField", IsRequired=true)]
        public string MeinVZPersonIdk__BackingField {
            get {
                return this.MeinVZPersonIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MeinVZPersonIdk__BackingFieldField, value) != true)) {
                    this.MeinVZPersonIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("MeinVZPersonIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<StayFriendsPersonId>k__BackingField", IsRequired=true)]
        public string StayFriendsPersonIdk__BackingField {
            get {
                return this.StayFriendsPersonIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.StayFriendsPersonIdk__BackingFieldField, value) != true)) {
                    this.StayFriendsPersonIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("StayFriendsPersonIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WerKenntWenUrl>k__BackingField", IsRequired=true)]
        public string WerKenntWenUrlk__BackingField {
            get {
                return this.WerKenntWenUrlk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.WerKenntWenUrlk__BackingFieldField, value) != true)) {
                    this.WerKenntWenUrlk__BackingFieldField = value;
                    this.RaisePropertyChanged("WerKenntWenUrlk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<XingProfileId>k__BackingField", IsRequired=true)]
        public string XingProfileIdk__BackingField {
            get {
                return this.XingProfileIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.XingProfileIdk__BackingFieldField, value) != true)) {
                    this.XingProfileIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("XingProfileIdk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountryCode", Namespace="http://schemas.datacontract.org/2004/07/Sem.Sync.SyncBase.DetailData")]
    public enum CountryCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Afghanistan = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Albania = 355,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Algeria = 213,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AmericanSamoa = 1684,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Andorra = 376,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Angola = 244,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Anguilla = 1264,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Antarctica = 672,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Antigua = 1268,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Argentina = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Armenia = 374,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aruba = 297,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ascension = 247,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Australia = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AustralianExternalTerritories = 672,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Austria = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Azerbaijan = 994,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bahamas = 1242,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bahrain = 973,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bangladesh = 880,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Barbados = 1246,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Barbuda = 1268,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Belarus = 375,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Belgium = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Belize = 501,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Benin = 229,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bermuda = 1441,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bhutan = 975,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bolivia = 591,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BosniaHerzegovina = 387,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Botswana = 267,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Brazil = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BritishVirginIslands = 1284,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BruneiDarussalam = 673,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bulgaria = 359,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BurkinaFaso = 226,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Burundi = 257,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cambodia = 855,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cameroon = 237,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CapeVerdeIslands = 238,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CaymanIslands = 1345,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CentralAfricanRepublic = 236,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Chad = 235,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChathamIslandNewZealand = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Chile = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChinaPRC = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChristmasIsland = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CocosKeelingIslands = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Colombia = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Comoros = 269,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Congo = 242,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CongoDemRepof = 243,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CookIslands = 682,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CostaRica = 506,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CotedIvoireIvoryCoast = 225,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Croatia = 385,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cuba = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CubaGuantanamoBay = 5399,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Curacao = 599,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cyprus = 357,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CzechRepublic = 420,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Denmark = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DiegoGarcia = 246,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Djibouti = 253,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dominica = 1767,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DominicanRepublic = 1809,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DominicanRepublic2 = 1829,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EasterIsland = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EastTimor = 670,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ecuador = 593,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Egypt = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EllipsoMobileSatelliteservice = 17625,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ElSalvador = 503,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMSATMobileSatelliteservice = 88213,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EquatorialGuinea = 240,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eritrea = 291,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Estonia = 372,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ethiopia = 251,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FalklandIslandsMalvinas = 500,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FaroeIslands = 298,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FijiIslands = 679,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finland = 358,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        France = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FrenchAntilles = 596,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FrenchGuiana = 594,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FrenchPolynesia = 689,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GaboneseRepublic = 241,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gambia = 220,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Georgia = 995,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Germany = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ghana = 233,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gibraltar = 350,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlobalMobileSatelliteSystemGMSS = 881,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlobalstarMobileSatelliteService = 17637,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Greece = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Greenland = 299,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Grenada = 1473,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Guadeloupe = 590,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Guam = 1671,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GuantanamoBay = 5399,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Guatemala = 502,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Guinea = 224,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GuineaBissau = 245,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Guyana = 592,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Haiti = 509,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Honduras = 504,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HongKong = 852,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hungary = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Iceland = 354,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ICOGlobalMobileSatelliteService = 17621,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        India = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Indonesia = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InmarsatAtlanticOceanEast = 871,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InmarsatAtlanticOceanWest = 874,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InmarsatIndianOcean = 873,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InmarsatPacificOcean = 872,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InmarsatSNAC = 870,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternationalFreephoneService = 800,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternationalSharedCostServiceISCS = 808,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Iran = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Iraq = 964,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ireland = 353,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IridiumMobileSatelliteservice = 17633,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Israel = 972,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Italy = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jamaica = 1876,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Japan = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jordan = 962,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kenya = 254,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kiribati = 686,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KoreaNorth = 850,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KoreaSouth = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kuwait = 965,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KyrgyzRepublic = 996,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Laos = 856,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Latvia = 371,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lebanon = 961,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lesotho = 266,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Liberia = 231,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Libya = 218,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Liechtenstein = 423,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lithuania = 370,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Luxembourg = 352,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Macao = 853,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MacedoniaFormerYugoslavRepof = 389,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Madagascar = 261,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Malawi = 265,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Malaysia = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Maldives = 960,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaliRepublic = 223,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Malta = 356,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MarshallIslands = 692,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Martinique = 596,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mauritania = 222,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mauritius = 230,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MayotteIsland = 269,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mexico = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MicronesiaFederalStatesOf = 691,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MidwayIsland = 1808,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Moldova = 373,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monaco = 377,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mongolia = 976,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Montenegro = 382,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Montserrat = 1664,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Morocco = 212,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mozambique = 258,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Myanmar = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Namibia = 264,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nauru = 674,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nepal = 977,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Netherlands = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NetherlandsAntilles = 599,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nevis = 1869,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NewCaledonia = 687,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NewZealand = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nicaragua = 505,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Niger = 227,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nigeria = 234,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Niue = 683,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NorfolkIsland = 672,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NorthernMarianasIslands = 1670,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Norway = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Oman = 968,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pakistan = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Palau = 680,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PalestinianSettlements = 970,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Panama = 507,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PapuaNewGuinea = 675,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paraguay = 595,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Peru = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Philippines = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Poland = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Portugal = 351,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PuertoRico = 1787,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PuertoRico2 = 1939,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Qatar = 974,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RéunionIsland = 262,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Romania = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RussiaKazakhstan = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RwandeseRepublic = 250,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Samoa = 685,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SanMarino = 378,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SaoTomeandPrincipe = 239,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SaudiArabia = 966,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Senegal = 221,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Serbia = 381,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SeychellesRepublic = 248,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SierraLeone = 232,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Singapore = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SlovakRepublic = 421,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Slovenia = 386,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolomonIslands = 677,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SomaliDemocraticRepublic = 252,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SouthAfrica = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spain = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SriLanka = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StHelena = 290,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StKittsNevis = 1869,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StLucia = 1758,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StPierreMiquelon = 508,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StVincentGrenadines = 1784,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sudan = 249,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suriname = 597,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Swaziland = 268,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sweden = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Switzerland = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Syria = 963,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Taiwan = 886,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tajikistan = 992,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tanzania = 255,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thailand = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThurayaMobileSatelliteservice = 88216,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimorLeste = 670,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TogoleseRepublic = 228,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tokelau = 690,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TongaIslands = 676,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TrinidadTobago = 1868,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tunisia = 216,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Turkey = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Turkmenistan = 993,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurksandCaicosIslands = 1649,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tuvalu = 688,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uganda = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ukraine = 380,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnitedArabEmirates = 971,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnitedKingdom = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnitedStatesofAmericaCanada = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UniversalPersonalTelecommunicationsUPT = 878,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        unknown175 = 175,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        unspecified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uruguay = 598,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USVirginIslands = 1340,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uzbekistan = 998,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vanuatu = 678,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VaticanCity = 418,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Venezuela = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vietnam = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WakeIsland = 808,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WallisandFutunaIslands = 681,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yemen = 967,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zambia = 260,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zanzibar = 255,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zimbabwe = 263,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://svenerikmatzen.com/Sem/Sync/OnlineStorage", ConfigurationName="OnlineStorage.IContact")]
    public interface IContact {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://svenerikmatzen.com/Sem/Sync/OnlineStorage/IContact/GetAll", ReplyAction="http://svenerikmatzen.com/Sem/Sync/OnlineStorage/IContact/GetAllResponse")]
        Sem.Sync.Connector.OnlineStorage.OnlineStorage.ContactListContainer GetAll(string clientFolderName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://svenerikmatzen.com/Sem/Sync/OnlineStorage/IContact/WriteFullList", ReplyAction="http://svenerikmatzen.com/Sem/Sync/OnlineStorage/IContact/WriteFullListResponse")]
        bool WriteFullList(Sem.Sync.Connector.OnlineStorage.OnlineStorage.ContactListContainer elements, string clientFolderName, bool skipIfExisting);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactChannel : Sem.Sync.Connector.OnlineStorage.OnlineStorage.IContact, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactClient : System.ServiceModel.ClientBase<Sem.Sync.Connector.OnlineStorage.OnlineStorage.IContact>, Sem.Sync.Connector.OnlineStorage.OnlineStorage.IContact {
        
        public ContactClient() {
        }
        
        public ContactClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sem.Sync.Connector.OnlineStorage.OnlineStorage.ContactListContainer GetAll(string clientFolderName) {
            return base.Channel.GetAll(clientFolderName);
        }
        
        public bool WriteFullList(Sem.Sync.Connector.OnlineStorage.OnlineStorage.ContactListContainer elements, string clientFolderName, bool skipIfExisting) {
            return base.Channel.WriteFullList(elements, clientFolderName, skipIfExisting);
        }
    }
}
