// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Sdx.Sync.Connector.OracleCrmOnDemand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#IgnoreCertificateError")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#QueryContactsByFilter(System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClient.#ReadFullList(System.String,System.Collections.Generic.List`1<Sem.Sync.SyncBase.StdElement>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClientConfigurationData.#FilterList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClient.#AddRange(System.Collections.Generic.List`1<Sem.Sync.SyncBase.DetailData.StdElement>,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClient.#ReadFullList(System.String,System.Collections.Generic.List`1<Sem.Sync.SyncBase.DetailData.StdElement>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClient.#WriteFullList(System.Collections.Generic.List`1<Sem.Sync.SyncBase.DetailData.StdElement>,System.String,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#UpdateContacts(System.Collections.Generic.IEnumerable`1<Sdx.Sync.Connector.OracleCrmOnDemand.ContactSR.ContactData>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Sem.Sync.SyncBase.SyncComponent.LogProcessingEvent(System.String)", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#LogOff()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Sem.Sync.SyncBase.SyncComponent.LogProcessingEvent(System.String)", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#LogOn(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Sem.Sync.SyncBase.SyncComponent.LogProcessingEvent(System.String)", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#QueryAccountsByFilter(System.Collections.Generic.IEnumerable`1<Sem.GenericHelpers.Entities.KeyValuePair>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Sem.Sync.SyncBase.SyncComponent.LogProcessingEvent(System.String,System.Object[])", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#QueryAccountsByFilter(System.Collections.Generic.IEnumerable`1<Sem.GenericHelpers.Entities.KeyValuePair>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Sem.Sync.SyncBase.SyncComponent.LogProcessingEvent(System.String)", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#QueryContactsByFilter(System.Collections.Generic.IEnumerable`1<Sem.GenericHelpers.Entities.KeyValuePair>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Sem.Sync.SyncBase.SyncComponent.LogProcessingEvent(System.String,System.Object[])", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#QueryContactsByFilter(System.Collections.Generic.IEnumerable`1<Sem.GenericHelpers.Entities.KeyValuePair>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Sem.Sync.SyncBase.SyncComponent.LogProcessingEvent(System.String)", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#UpdateContacts(System.Collections.Generic.IEnumerable`1<Sdx.Sync.Connector.OracleCrmOnDemand.ContactSR.ContactData>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Sem.Sync.SyncBase.SyncComponent.LogProcessingEvent(System.String,System.Object[])", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#UpdateContacts(System.Collections.Generic.IEnumerable`1<Sdx.Sync.Connector.OracleCrmOnDemand.ContactSR.ContactData>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Sem.Sync.SyncBase.SyncComponent.LogProcessingEvent(System.String)", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClient.#ReadFullList(System.String,System.Collections.Generic.List`1<Sem.Sync.SyncBase.DetailData.StdElement>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Sem.Sync.SyncBase.SyncComponent.LogProcessingEvent(System.String,System.Object[])", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClient.#ReadFullList(System.String,System.Collections.Generic.List`1<Sem.Sync.SyncBase.DetailData.StdElement>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Sem.Sync.SyncBase.SyncComponent.LogProcessingEvent(System.String)", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClient.#WriteFullList(System.Collections.Generic.List`1<Sem.Sync.SyncBase.DetailData.StdElement>,System.String,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Sem.Sync.SyncBase.SyncComponent.LogProcessingEvent(System.String,System.Object[])", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClient.#WriteFullList(System.Collections.Generic.List`1<Sem.Sync.SyncBase.DetailData.StdElement>,System.String,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClientConfigurationEditor.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.MaskedTextBox.set_Mask(System.String)", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClientConfigurationEditor.#InitializeComponent()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.Constants.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#GetClient`1()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactAccess.#LogOn(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClientConfiguration.#ShowConfigurationDialog(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClientConfigurationData.#FilterList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Sdx.Sync.Connector.OracleCrmOnDemand.ContactClientConfigurationEditor.#ShowDialog(Sdx.Sync.Connector.OracleCrmOnDemand.ContactClientConfigurationData)")]
