//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem.Sync.SyncBase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sem.Sync.SyncBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: .
        /// </summary>
        public static string ErrorMessageFileNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while unmatching.
        /// </summary>
        public static string ExceptionWhileUnmatchingCaption {
            get {
                return ResourceManager.GetString("ExceptionWhileUnmatchingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exception while execution: 
        ///{0}.
        /// </summary>
        public static string MessageErrorException {
            get {
                return ResourceManager.GetString("MessageErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished - Press ENTER to close the window.
        /// </summary>
        public static string MessageInfoCloseWithEnter {
            get {
                return ResourceManager.GetString("MessageInfoCloseWithEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading command list: {0}.
        /// </summary>
        public static string MessageInfoLoadingList {
            get {
                return ResourceManager.GetString("MessageInfoLoadingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% done....
        /// </summary>
        public static string MessageInfoProgress {
            get {
                return ResourceManager.GetString("MessageInfoProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution status: {0}.
        /// </summary>
        public static string MessageInfoStatus {
            get {
                return ResourceManager.GetString("MessageInfoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage: {0} [PathOfCommandList].
        /// </summary>
        public static string MessageInfoUsage {
            get {
                return ResourceManager.GetString("MessageInfoUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to working folder: {0}.
        /// </summary>
        public static string MessageInfoWorkingFolder {
            get {
                return ResourceManager.GetString("MessageInfoWorkingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -=&gt; YES.
        /// </summary>
        public static string MessageUiDispatcherAskForConfirm {
            get {
                return ResourceManager.GetString("MessageUiDispatcherAskForConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem finding the Primary Interop Assemblies for Office. Do you want to open the download page for this missing dependency?.
        /// </summary>
        public static string MissingInteropQuestion {
            get {
                return ResourceManager.GetString("MissingInteropQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string MissingInteropQuestionTitle {
            get {
                return ResourceManager.GetString("MissingInteropQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding element ....
        /// </summary>
        public static string uiAddingElement {
            get {
                return ResourceManager.GetString("uiAddingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding missing element ....
        /// </summary>
        public static string uiAddingMissingElement {
            get {
                return ResourceManager.GetString("uiAddingMissingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding missing elements ....
        /// </summary>
        public static string uiAddingMissingElements {
            get {
                return ResourceManager.GetString("uiAddingMissingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding {0} elements ....
        /// </summary>
        public static string uiAddingXElements {
            get {
                return ResourceManager.GetString("uiAddingXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding {0} elements ....
        /// </summary>
        public static string uiAddingXMissingElements {
            get {
                return ResourceManager.GetString("uiAddingXMissingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to improve the software quality, the program wants to send the following information to the web site www.svenerikmatzen.info:.
        /// </summary>
        public static string UiDispatcherAskForConfirmSendingException01 {
            get {
                return ResourceManager.GetString("UiDispatcherAskForConfirmSendingException01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;Y&quot; and the RETURN key to send the information, enter &quot;N&quot; to not send the information..
        /// </summary>
        public static string UiDispatcherAskForConfirmSendingException02 {
            get {
                return ResourceManager.GetString("UiDispatcherAskForConfirmSendingException02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element added.
        /// </summary>
        public static string uiElementAdded {
            get {
                return ResourceManager.GetString("uiElementAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element skipped.
        /// </summary>
        public static string uiElementSkipped {
            get {
                return ResourceManager.GetString("uiElementSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files deleted.
        /// </summary>
        public static string uiFilesDeleted {
            get {
                return ResourceManager.GetString("uiFilesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging on ....
        /// </summary>
        public static string uiLogOn {
            get {
                return ResourceManager.GetString("uiLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normalizing ....
        /// </summary>
        public static string uiNormalizing {
            get {
                return ResourceManager.GetString("uiNormalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of sync engine is outdated - please update!.
        /// </summary>
        public static string uiOutOfDateVersion {
            get {
                return ResourceManager.GetString("uiOutOfDateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processing canceled..
        /// </summary>
        public static string uiProcessingCanceled {
            get {
                return ResourceManager.GetString("uiProcessingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading elements ....
        /// </summary>
        public static string uiReadingElements {
            get {
                return ResourceManager.GetString("uiReadingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorted.
        /// </summary>
        public static string uiSorted {
            get {
                return ResourceManager.GetString("uiSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorting ....
        /// </summary>
        public static string uiSorting {
            get {
                return ResourceManager.GetString("uiSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start processing {0} sync commands....
        /// </summary>
        public static string uiStartingProcessing {
            get {
                return ResourceManager.GetString("uiStartingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writing Elements.
        /// </summary>
        public static string uiWritingElements {
            get {
                return ResourceManager.GetString("uiWritingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writing done.
        /// </summary>
        public static string uiWritingElementsDone {
            get {
                return ResourceManager.GetString("uiWritingElementsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} elements added.
        /// </summary>
        public static string uiXElementsAdded {
            get {
                return ResourceManager.GetString("uiXElementsAdded", resourceCulture);
            }
        }
    }
}
