//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem.Sync.Connector.LotusNotes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sem.Sync.Connector.LotusNotes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem finding the Primary Interop Assemblies for Office 2003. Do you want to open the download page for this missing dependency?.
        /// </summary>
        internal static string _MissingInteropQuestion {
            get {
                return ResourceManager.GetString("_MissingInteropQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found .
        /// </summary>
        internal static string _MissingInteropQuestionTitle {
            get {
                return ResourceManager.GetString("_MissingInteropQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no translation for this value into the SemSync namespace..
        /// </summary>
        internal static string _NoValueTranslationMessage {
            get {
                return ResourceManager.GetString("_NoValueTranslationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problem accessing outlook store at name {0}: {1}.
        /// </summary>
        internal static string _uiProblemAccessingOutlookStore {
            get {
                return ResourceManager.GetString("_uiProblemAccessingOutlookStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove duplicates finished.
        /// </summary>
        internal static string _uiRemoveDuplicates {
            get {
                return ResourceManager.GetString("_uiRemoveDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removing ....
        /// </summary>
        internal static string _uiRemoving {
            get {
                return ResourceManager.GetString("_uiRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one item cannot be saved.
        /// </summary>
        internal static string _UserInfoElementCannotBeSaved {
            get {
                return ResourceManager.GetString("_UserInfoElementCannotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no outlook folder selected.
        /// </summary>
        internal static string _UserInfoNoOutlookFolderSelected {
            get {
                return ResourceManager.GetString("_UserInfoNoOutlookFolderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problem accessing outlook store at name {0}: {1}.
        /// </summary>
        internal static string _UserInfoProblemAccessingStore {
            get {
                return ResourceManager.GetString("_UserInfoProblemAccessingStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove duplicates finished.
        /// </summary>
        internal static string _UserInfoRemoveDuplicatesFinished {
            get {
                return ResourceManager.GetString("_UserInfoRemoveDuplicatesFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding {0} elements ....
        /// </summary>
        internal static string uiAddingXElements {
            get {
                return ResourceManager.GetString("uiAddingXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comparing ....
        /// </summary>
        internal static string uiComparing {
            get {
                return ResourceManager.GetString("uiComparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact updated..
        /// </summary>
        internal static string uiContactUpdated {
            get {
                return ResourceManager.GetString("uiContactUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at name {0}: {1}.
        /// </summary>
        internal static string uiErrorAtName {
            get {
                return ResourceManager.GetString("uiErrorAtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging on ....
        /// </summary>
        internal static string uiLogginIn {
            get {
                return ResourceManager.GetString("uiLogginIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no lotus notes {0} view found.
        /// </summary>
        internal static string uiNoViewFound {
            get {
                return ResourceManager.GetString("uiNoViewFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preparing list ....
        /// </summary>
        internal static string uiPreparingList {
            get {
                return ResourceManager.GetString("uiPreparingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading {0} ....
        /// </summary>
        internal static string uiReadingContact {
            get {
                return ResourceManager.GetString("uiReadingContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching ....
        /// </summary>
        internal static string uiSearching {
            get {
                return ResourceManager.GetString("uiSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} elements added.
        /// </summary>
        internal static string uiXElementsAdded {
            get {
                return ResourceManager.GetString("uiXElementsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding/updating {0} elements ....
        /// </summary>
        internal static string UserInfoAddingEntries {
            get {
                return ResourceManager.GetString("UserInfoAddingEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comparing ....
        /// </summary>
        internal static string UserInfoComparing {
            get {
                return ResourceManager.GetString("UserInfoComparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} elements added, {1} elements updated.
        /// </summary>
        internal static string UserInfoElementsAdded {
            get {
                return ResourceManager.GetString("UserInfoElementsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at name {0}: {1}.
        /// </summary>
        internal static string UserInfoErrorAtName {
            get {
                return ResourceManager.GetString("UserInfoErrorAtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging on ....
        /// </summary>
        internal static string UserInfoLoggingOn {
            get {
                return ResourceManager.GetString("UserInfoLoggingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preparing list ....
        /// </summary>
        internal static string UserInfoPreparingList {
            get {
                return ResourceManager.GetString("UserInfoPreparingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading ... .
        /// </summary>
        internal static string UserInfoReading {
            get {
                return ResourceManager.GetString("UserInfoReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removing ....
        /// </summary>
        internal static string UserInfoRemoving {
            get {
                return ResourceManager.GetString("UserInfoRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching ....
        /// </summary>
        internal static string UserInfoSearchingElementInStore {
            get {
                return ResourceManager.GetString("UserInfoSearchingElementInStore", resourceCulture);
            }
        }
    }
}
